-- =============================================================================
-- SERVICE CATALOGUE — PostgreSQL canonical schema
-- 01_platform.sql | schema: platform
-- Converted from backend/db/00_platform.sql
-- =============================================================================

SET search_path TO platform, public;

CREATE TABLE IF NOT EXISTS app_config (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_key   VARCHAR(100) NOT NULL UNIQUE,
    config_value TEXT NULL,
    config_type  VARCHAR(20) NULL DEFAULT 'string'
                 CHECK (config_type IN ('string', 'json', 'boolean', 'number') OR config_type IS NULL),
    description  VARCHAR(500) NULL,
    is_sensitive BOOLEAN NOT NULL DEFAULT FALSE,
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by   VARCHAR(200) NULL
);

CREATE TABLE IF NOT EXISTS users (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR(100) NOT NULL UNIQUE,
    display_name    VARCHAR(200) NULL,
    email           VARCHAR(255) NULL,
    role            VARCHAR(20)  NOT NULL DEFAULT 'viewer'
                    CHECK (role IN ('viewer', 'editor', 'admin')),
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    preferred_lang  VARCHAR(5)  NULL DEFAULT 'cz',
    preferred_theme VARCHAR(10) NULL DEFAULT 'dark',
    auth_provider   VARCHAR(20) NOT NULL DEFAULT 'local'
                    CHECK (auth_provider IN ('local', 'ad')),
    external_principal VARCHAR(255) NULL,
    password_hash   VARCHAR(200) NULL,
    given_name      VARCHAR(100) NULL,
    surname         VARCHAR(100) NULL,
    phone           VARCHAR(50) NULL,
    department      VARCHAR(200) NULL,
    avatar_color    VARCHAR(20) NULL,
    last_login_at   TIMESTAMPTZ NULL,
    last_sso_login_at TIMESTAMPTZ NULL,
    last_login_ip   VARCHAR(50) NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS refresh_tokens (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash  VARCHAR(500) NOT NULL,
    expires_at  TIMESTAMPTZ NOT NULL,
    revoked_at  TIMESTAMPTZ NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS audit_log (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name     VARCHAR(100) NOT NULL,
    record_id      INTEGER NOT NULL,
    record_label   VARCHAR(255) NULL,
    action         VARCHAR(20) NOT NULL CHECK (
                     action IN (
                       'INSERT','UPDATE','DELETE','SOFT_DELETE',
                       'RESTORE','SP_IMPORT','JSON_IMPORT','SCORE_RECALC'
                     )
                   ),
    old_values     TEXT NULL,
    new_values     TEXT NULL,
    changed_fields TEXT NULL,
    performed_by   VARCHAR(200) NULL,
    performed_at   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    client_ip      VARCHAR(50) NULL,
    user_agent     VARCHAR(500) NULL
);

CREATE INDEX IF NOT EXISTS ix_refresh_tokens_hash
    ON refresh_tokens(token_hash)
    WHERE revoked_at IS NULL;

CREATE INDEX IF NOT EXISTS ix_refresh_tokens_expires
    ON refresh_tokens(expires_at)
    WHERE revoked_at IS NULL;

CREATE INDEX IF NOT EXISTS ix_refresh_tokens_user_id
    ON refresh_tokens(user_id);

CREATE INDEX IF NOT EXISTS ix_users_active
    ON users(username)
    WHERE is_active = TRUE;

CREATE UNIQUE INDEX IF NOT EXISTS ux_users_external_principal
    ON users(external_principal)
    WHERE external_principal IS NOT NULL;

CREATE INDEX IF NOT EXISTS ix_users_auth_provider_active
    ON users(auth_provider, is_active, username);

CREATE INDEX IF NOT EXISTS ix_audit_log_record
    ON audit_log(table_name, record_id, performed_at DESC);

CREATE INDEX IF NOT EXISTS ix_audit_log_user
    ON audit_log(performed_by, performed_at DESC);

CREATE INDEX IF NOT EXISTS ix_audit_log_time
    ON audit_log(performed_at DESC);

CREATE OR REPLACE FUNCTION cleanup_expired_tokens()
RETURNS TABLE(deleted_count INTEGER)
LANGUAGE plpgsql
AS $$
DECLARE
    affected_rows INTEGER;
BEGIN
    DELETE FROM refresh_tokens
    WHERE expires_at < CURRENT_TIMESTAMP OR revoked_at IS NOT NULL;

    GET DIAGNOSTICS affected_rows = ROW_COUNT;
    RETURN QUERY SELECT affected_rows;
END;
$$;

CREATE OR REPLACE FUNCTION trim_audit_log(p_retention_days INTEGER DEFAULT 365)
RETURNS TABLE(deleted_count INTEGER, cutoff_date TIMESTAMPTZ)
LANGUAGE plpgsql
AS $$
DECLARE
    affected_rows INTEGER;
    cutoff TIMESTAMPTZ;
BEGIN
    cutoff := CURRENT_TIMESTAMP - make_interval(days => p_retention_days);

    DELETE FROM audit_log
    WHERE performed_at < cutoff;

    GET DIAGNOSTICS affected_rows = ROW_COUNT;
    RETURN QUERY SELECT affected_rows, cutoff;
END;
$$;

INSERT INTO app_config (config_key, config_value, config_type, description)
VALUES
    ('catalog.model.version',           'v2.1-graph-pricing-sla-taxonomy', 'string',  'Canonical model version'),
    ('import.parser.version',           '1',                               'number',  'Current CSV import parser version'),
    ('import.store_raw_fields',         'true',                            'boolean', 'Store raw source fields for audit and re-parse'),
    ('graph.default_relation_confidence','1.0',                           'number',  'Default confidence for explicit relations'),
    ('app.version',                     '2.1.0',                           'string',  'Application version'),
    ('app.default_lang',                'cz',                              'string',  'Default UI language (cz / en)'),
    ('app.default_theme',               'dark',                            'string',  'Default UI theme (dark / light)'),
    ('auth.jwt_expiry_minutes',         '60',                              'number',  'Access token lifetime in minutes'),
    ('auth.refresh_expiry_days',        '7',                               'number',  'Refresh token lifetime in days'),
    ('auth.sso.enabled',                'false',                           'boolean', 'Enable trusted-header SSO login.'),
    ('auth.sso.header',                 'x-remote-user',                   'string',  'Trusted header carrying the authenticated AD identity.'),
    ('auth.sso.display_name_header',    'x-remote-name',                   'string',  'Trusted header carrying the display name.'),
    ('auth.sso.email_header',           'x-remote-email',                  'string',  'Trusted header carrying the email address.'),
    ('auth.sso.given_name_header',      'x-remote-given-name',             'string',  'Trusted header carrying the given name.'),
    ('auth.sso.surname_header',         'x-remote-surname',                'string',  'Trusted header carrying the surname.'),
    ('auth.sso.department_header',      'x-remote-department',             'string',  'Trusted header carrying the department.'),
    ('c3.sync_enabled',                 'false',                           'boolean', 'Enable automatic C3 Taxonomy synchronization'),
    ('c3.sync_interval_hours',          '24',                              'number',  'C3 synchronization interval in hours'),
    ('cache.dashboard_ttl_sec',         '300',                             'number',  'Dashboard statistics cache TTL in seconds')
ON CONFLICT (config_key) DO UPDATE SET
    config_value = EXCLUDED.config_value,
    config_type = EXCLUDED.config_type,
    description = EXCLUDED.description,
    updated_at = CURRENT_TIMESTAMP;
