-- =============================================================================
-- SERVICE CATALOGUE — PostgreSQL canonical schema
-- 03_groups.sql | schema: platform
-- Converted from backend/db/52_groups.sql
-- =============================================================================

SET search_path TO platform, public;

CREATE TABLE IF NOT EXISTS app_group (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_code  VARCHAR(50)  NOT NULL UNIQUE,
    group_name  VARCHAR(200) NOT NULL,
    description TEXT NULL,
    is_active   BOOLEAN NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS app_group_permission (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id   INTEGER NOT NULL REFERENCES app_group(id) ON DELETE CASCADE,
    scope      VARCHAR(50)  NOT NULL,
    permission VARCHAR(50)  NOT NULL,
    resource   VARCHAR(200) NOT NULL,
    CONSTRAINT uq_agp_unique UNIQUE (group_id, scope, permission, resource)
);

CREATE INDEX IF NOT EXISTS ix_agp_group_id
    ON app_group_permission(group_id);

CREATE TABLE IF NOT EXISTS app_user_group (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_sub    VARCHAR(200) NOT NULL,
    group_id    INTEGER NOT NULL REFERENCES app_group(id) ON DELETE CASCADE,
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    assigned_by VARCHAR(200) NULL,
    CONSTRAINT uq_aug_user_group UNIQUE (user_sub, group_id)
);

INSERT INTO app_group (group_code, group_name, description, is_active)
VALUES ('administrators', 'Administrators', 'Full access to all columns and ref data', TRUE)
ON CONFLICT (group_code) DO UPDATE SET
    group_name = EXCLUDED.group_name,
    description = EXCLUDED.description,
    is_active = EXCLUDED.is_active,
    updated_at = CURRENT_TIMESTAMP;
