-- =============================================================================
-- SERVICE CATALOGUE — PostgreSQL canonical schema
-- 04_core.sql | schema: data
-- Converted from backend/db/02_core.sql
-- =============================================================================

SET search_path TO data, public;

CREATE TABLE IF NOT EXISTS service_catalog (
    id                            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id                    VARCHAR(50)   NOT NULL UNIQUE,
    title                         VARCHAR(255)  NOT NULL,
    short_description             VARCHAR(1000) NULL,
    description                   TEXT          NULL,
    service_type_code             VARCHAR(50)   NULL REFERENCES ref_service_type(code),
    service_status_code           VARCHAR(50)   NULL REFERENCES ref_service_status(code),
    catalogue_version             VARCHAR(50)   NULL,
    portfolio_group_code          VARCHAR(100)  NULL REFERENCES ref_portfolio_group(code),
    global_service_group_code     VARCHAR(150)  NULL REFERENCES ref_global_service_group(code),
    service_line_code             VARCHAR(150)  NULL REFERENCES ref_service_line(code),
    organizational_element_code   VARCHAR(150)  NULL REFERENCES ref_organizational_element(code),
    service_url                   VARCHAR(2000) NULL,
    security_classification_code  VARCHAR(30)   NULL REFERENCES ref_security_classification(code),
    value_proposition             TEXT          NULL,
    service_features              TEXT          NULL,
    business_purpose              TEXT          NULL,
    scope_text                    TEXT          NULL,
    unit_of_measure               VARCHAR(100)  NULL,
    charging_basis                VARCHAR(255)  NULL,
    rate_note                     TEXT          NULL,
    ordering_note                 TEXT          NULL,
    exclusions                    TEXT          NULL,
    sla_availability              DECIMAL(5,2)  NULL,
    sla_restoration_hours         INTEGER       NULL,
    sla_delivery_days             INTEGER       NULL,
    sla_restoration_text          TEXT          NULL,
    sla_delivery_text             TEXT          NULL,
    graph_x                       DOUBLE PRECISION NULL,
    graph_y                       DOUBLE PRECISION NULL,
    operational_notes_raw         TEXT          NULL,
    support_locations_raw         TEXT          NULL,
    request_process_raw           TEXT          NULL,
    support_availability_raw      TEXT          NULL,
    service_cost_raw              TEXT          NULL,
    additional_information_raw    TEXT          NULL,
    retired_note                  TEXT          NULL,
    cp_service_type_raw           VARCHAR(255)  NULL,
    service_features_raw          TEXT          NULL,
    ext_tools_raw                 TEXT          NULL,
    legacy_ssl_mapping_raw        TEXT          NULL,
    budget_activity_code          VARCHAR(100)  NULL,
    other_info_raw                TEXT          NULL,
    pricing_note_raw              TEXT          NULL,
    is_available_status_ambiguous BOOLEAN       NOT NULL DEFAULT FALSE,
    service_area_raw              TEXT          NULL,
    is_stub                       BOOLEAN       NOT NULL DEFAULT FALSE,
    customer_type_json            TEXT          NULL,
    options_json                  TEXT          NULL,
    notes_json                    TEXT          NULL,
    training_refs_json            TEXT          NULL,
    prerequisites_json            TEXT          NULL,
    dependencies_json             TEXT          NULL,
    source_local_id               VARCHAR(100)  NULL,
    source_sp_id                  INTEGER       NULL,
    source_etag                   VARCHAR(255)  NULL,
    created_at_source             TIMESTAMPTZ   NULL,
    modified_at_source            TIMESTAMPTZ   NULL,
    is_deleted                    BOOLEAN       NOT NULL DEFAULT FALSE,
    completeness_score            DECIMAL(5,2)  NULL,
    created_at                    TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                    TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by                    VARCHAR(255)  NULL,
    updated_by                    VARCHAR(255)  NULL
);

COMMENT ON COLUMN service_catalog.cp_service_type_raw IS
    'D1: Raw CSV "CP Service Type" value. "Retired" maps to service_status_code=retired, not service_type_code.';
COMMENT ON COLUMN service_catalog.is_available_status_ambiguous IS
    'D2: TRUE when "Not Available" was mapped to planned. Governance queue: WHERE is_available_status_ambiguous = TRUE.';
COMMENT ON COLUMN service_catalog.service_area_raw IS
    'D3: Raw "Service Area" without FK. FK deferred; overlap with service_line/organizational_element is unresolved.';
COMMENT ON COLUMN service_catalog.is_stub IS
    'D4: Placeholder for external refs and parent stubs. Hidden in UI (WHERE is_stub = FALSE).';
