-- =============================================================================
-- SERVICE CATALOGUE — PostgreSQL canonical schema
-- 05_graph.sql | schema: data
-- Converted from backend/db/03_graph.sql
-- =============================================================================

SET search_path TO data, public;

CREATE TABLE IF NOT EXISTS service_relation_raw (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id     BIGINT        NOT NULL REFERENCES service_catalog(id),
    source_field   VARCHAR(100)  NOT NULL,
    raw_value      TEXT          NOT NULL,
    parser_version VARCHAR(50)   NULL,
    parsed_ok      BOOLEAN       NOT NULL DEFAULT FALSE,
    parsed_at      TIMESTAMPTZ   NULL,
    notes          TEXT          NULL,
    created_at     TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS service_relation (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_service_id      BIGINT       NOT NULL REFERENCES service_catalog(id),
    to_service_id        BIGINT       NOT NULL REFERENCES service_catalog(id),
    relation_type_code   VARCHAR(50)  NOT NULL REFERENCES ref_relation_type(code),
    pace_code            VARCHAR(10)  NULL REFERENCES ref_pace_category(code),
    pace_code_normalized VARCHAR(10)  GENERATED ALWAYS AS (COALESCE(pace_code, 'NONE')) STORED,
    is_mandatory         BOOLEAN      NOT NULL DEFAULT TRUE,
    impact_mode          VARCHAR(30)  NOT NULL DEFAULT 'hard_stop',
    impact_level         VARCHAR(20)  NOT NULL DEFAULT 'high',
    relation_label       VARCHAR(255) NULL,
    relation_note        TEXT         NULL,
    source_field         VARCHAR(100) NULL,
    raw_text             TEXT         NULL,
    parse_confidence     DECIMAL(5,4) NULL,
    is_inferred          BOOLEAN      NOT NULL DEFAULT FALSE,
    is_verified          BOOLEAN      NOT NULL DEFAULT FALSE,
    valid_from           TIMESTAMPTZ  NULL,
    valid_to             TIMESTAMPTZ  NULL,
    source_local_id      VARCHAR(100) NULL,
    source_sp_id         INTEGER      NULL,
    source_etag          VARCHAR(255) NULL,
    is_deleted           BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at           TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by           VARCHAR(255) NULL,
    CONSTRAINT chk_service_relation_no_self_loop CHECK (from_service_id <> to_service_id)
);
