-- =============================================================================
-- SERVICE CATALOGUE — PostgreSQL canonical schema
-- 06_pricing.sql | schema: data
-- Converted from backend/db/04_pricing.sql
-- =============================================================================

SET search_path TO data, public;

CREATE TABLE IF NOT EXISTS service_flavour (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id          BIGINT       NOT NULL REFERENCES service_catalog(id),
    flavour_code        VARCHAR(50)  NOT NULL,
    title               VARCHAR(255) NOT NULL,
    service_unit        VARCHAR(100) NULL,
    price_value         DECIMAL(18,2) NULL,
    currency_code       VARCHAR(10)  NULL DEFAULT 'EUR',
    billing_period_code VARCHAR(30)  NULL,
    initiation_cost     DECIMAL(18,2) NULL,
    lifecycle_cost      DECIMAL(18,2) NULL,
    lifetime_years      INTEGER      NULL,
    nations_rate        TEXT         NULL,
    dependency_text     TEXT         NULL,
    short_note          TEXT         NULL,
    pricing_note_raw    TEXT         NULL,
    delivery_note       TEXT         NULL,
    technical_note      TEXT         NULL,
    flavour_status_code VARCHAR(50)  NULL REFERENCES ref_flavour_status(code),
    display_order       INTEGER      NULL,
    is_orderable        BOOLEAN      NOT NULL DEFAULT TRUE,
    source_local_id     VARCHAR(100) NULL,
    is_deleted          BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_service_flavour_service_flavour_code
    ON service_flavour(service_id, flavour_code)
    WHERE is_deleted = FALSE;

CREATE TABLE IF NOT EXISTS service_sla (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id          BIGINT       NOT NULL REFERENCES service_catalog(id),
    flavour_id          BIGINT       NULL REFERENCES service_flavour(id),
    support_window_code VARCHAR(50)  NULL REFERENCES ref_support_window(code),
    availability_pct    DECIMAL(5,2) NULL,
    restoration_hours   INTEGER      NULL,
    delivery_days       INTEGER      NULL,
    priority_model_raw  TEXT         NULL,
    sla_note_raw        TEXT         NULL,
    source_field        VARCHAR(100) NULL,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP
);
