-- =============================================================================
-- SERVICE CATALOGUE — PostgreSQL canonical schema
-- 08_ownership.sql | schema: data
-- Converted from backend/db/06_ownership.sql
-- =============================================================================

SET search_path TO data, public;

CREATE TABLE IF NOT EXISTS service_role_assignment (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id        BIGINT       NOT NULL REFERENCES service_catalog(id),
    role_code         VARCHAR(50)  NOT NULL REFERENCES ref_service_role(code),
    display_name      VARCHAR(255) NOT NULL,
    email             VARCHAR(255) NULL,
    organization_name VARCHAR(255) NULL,
    valid_from        TIMESTAMPTZ  NULL,
    valid_to          TIMESTAMPTZ  NULL,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS service_c3_mapping (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id        BIGINT       NOT NULL REFERENCES service_catalog(id),
    c3_uuid           VARCHAR(100) NOT NULL,
    c3_parent_uuid    VARCHAR(100) NULL,
    c3_level          INTEGER      NULL,
    c3_domain         VARCHAR(255) NULL,
    c3_source         VARCHAR(255) NULL,
    c3_reference      VARCHAR(255) NULL,
    mapping_type_code VARCHAR(50)  NOT NULL REFERENCES ref_c3_mapping_type(code),
    pace_code         VARCHAR(10)  NULL REFERENCES ref_pace_category(code),
    is_primary        BOOLEAN      NOT NULL DEFAULT FALSE,
    mapping_note      TEXT         NULL,
    synced_at         TIMESTAMPTZ  NULL,
    sync_status       VARCHAR(50)  NULL,
    source_sp_id      INTEGER      NULL,
    source_etag       VARCHAR(255) NULL,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_service_c3_mapping_unique UNIQUE (service_id, c3_uuid, mapping_type_code, pace_code)
);

CREATE TABLE IF NOT EXISTS service_raw_field (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id     BIGINT       NOT NULL REFERENCES service_catalog(id),
    field_name     VARCHAR(100) NOT NULL,
    raw_value      TEXT         NULL,
    parsed_value   TEXT         NULL,
    parse_status   VARCHAR(50)  NULL,
    parser_version VARCHAR(50)  NULL,
    notes          TEXT         NULL,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS taxonomy_mapping_audit (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id      BIGINT       NOT NULL REFERENCES service_catalog(id),
    c3_uuid         VARCHAR(100) NULL,
    mapping_id      BIGINT       NULL,
    action_type     VARCHAR(30)  NOT NULL,
    changed_by      VARCHAR(200) NULL,
    old_values_json TEXT         NULL,
    new_values_json TEXT         NULL,
    changed_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS graph_layout_audit (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id  BIGINT       NOT NULL REFERENCES service_catalog(id),
    node_kind   VARCHAR(30)  NOT NULL,
    old_x       DOUBLE PRECISION NULL,
    old_y       DOUBLE PRECISION NULL,
    new_x       DOUBLE PRECISION NULL,
    new_y       DOUBLE PRECISION NULL,
    changed_by  VARCHAR(200) NULL,
    changed_at  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP
);
