-- =============================================================================
-- SERVICE CATALOGUE — PostgreSQL canonical schema
-- 09_import.sql | schema: data
-- Converted from backend/db/07_import.sql
-- =============================================================================

SET search_path TO data, public;

CREATE TABLE IF NOT EXISTS import_batch (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filename       VARCHAR(500) NOT NULL,
    imported_at    TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    imported_by    VARCHAR(255) NULL,
    row_count      INTEGER      NOT NULL DEFAULT 0,
    ok_count       INTEGER      NOT NULL DEFAULT 0,
    warn_count     INTEGER      NOT NULL DEFAULT 0,
    error_count    INTEGER      NOT NULL DEFAULT 0,
    parser_version VARCHAR(50)  NOT NULL DEFAULT '1.0',
    source_hash_sha256 VARCHAR(64) NULL,
    notes          TEXT         NULL
);

CREATE TABLE IF NOT EXISTS import_row (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id   BIGINT       NOT NULL REFERENCES import_batch(id),
    row_number INTEGER      NOT NULL,
    service_id VARCHAR(50)  NULL,
    raw_json   TEXT         NULL,
    status     VARCHAR(20)  NOT NULL CHECK (status IN ('ok', 'warn', 'error', 'skipped', 'processing')),
    created_at TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS import_issue (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id   BIGINT       NOT NULL REFERENCES import_batch(id),
    row_id     BIGINT       NULL REFERENCES import_row(id),
    service_id VARCHAR(50)  NULL,
    severity   VARCHAR(10)  NOT NULL CHECK (severity IN ('error', 'warn', 'info')),
    issue_code VARCHAR(100) NOT NULL,
    field_name VARCHAR(100) NULL,
    raw_value  TEXT         NULL,
    message    TEXT         NULL,
    resolved   BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS import_contract_report (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_name             VARCHAR(500) NOT NULL,
    source_kind             VARCHAR(50)  NOT NULL,
    created_by              VARCHAR(255) NULL,
    contract_version        VARCHAR(50)  NOT NULL DEFAULT '2026-03-30.import-v1',
    source_hash_sha256      VARCHAR(64)  NULL,
    item_count              INTEGER      NOT NULL DEFAULT 0,
    flavour_count           INTEGER      NOT NULL DEFAULT 0,
    explicit_relation_count INTEGER      NOT NULL DEFAULT 0,
    raw_prerequisite_count  INTEGER      NOT NULL DEFAULT 0,
    missing_target_count    INTEGER      NOT NULL DEFAULT 0,
    stub_count              INTEGER      NOT NULL DEFAULT 0,
    unresolved_ref_count    INTEGER      NOT NULL DEFAULT 0,
    unresolved_refs_json    TEXT         NULL,
    missing_targets_json    TEXT         NULL,
    summary_json            TEXT         NULL,
    created_at              TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE VIEW v_importcontractreport AS
SELECT
    id,
    source_name,
    source_kind,
    created_by,
    contract_version,
    source_hash_sha256,
    item_count,
    flavour_count,
    explicit_relation_count,
    raw_prerequisite_count,
    missing_target_count,
    stub_count,
    unresolved_ref_count,
    unresolved_refs_json,
    missing_targets_json,
    summary_json,
    created_at
FROM import_contract_report;

CREATE OR REPLACE VIEW v_importcontractreportlatest AS
SELECT
    id,
    source_name,
    source_kind,
    created_by,
    contract_version,
    source_hash_sha256,
    item_count,
    flavour_count,
    explicit_relation_count,
    raw_prerequisite_count,
    missing_target_count,
    stub_count,
    unresolved_ref_count,
    unresolved_refs_json,
    missing_targets_json,
    summary_json,
    created_at
FROM import_contract_report
ORDER BY created_at DESC, id DESC
LIMIT 1;

CREATE OR REPLACE VIEW v_importcontractreportbyhash AS
WITH ranked AS (
    SELECT
        id,
        source_name,
        source_kind,
        created_by,
        contract_version,
        source_hash_sha256,
        item_count,
        flavour_count,
        explicit_relation_count,
        raw_prerequisite_count,
        missing_target_count,
        stub_count,
        unresolved_ref_count,
        unresolved_refs_json,
        missing_targets_json,
        summary_json,
        created_at,
        ROW_NUMBER() OVER (PARTITION BY source_hash_sha256 ORDER BY created_at DESC, id DESC) AS rn
    FROM import_contract_report
    WHERE source_hash_sha256 IS NOT NULL
)
SELECT
    id,
    source_name,
    source_kind,
    created_by,
    contract_version,
    source_hash_sha256,
    item_count,
    flavour_count,
    explicit_relation_count,
    raw_prerequisite_count,
    missing_target_count,
    stub_count,
    unresolved_ref_count,
    unresolved_refs_json,
    missing_targets_json,
    summary_json,
    created_at
FROM ranked
WHERE rn = 1;

CREATE OR REPLACE VIEW v_importbatchsourcehash AS
SELECT
    id AS batch_id,
    filename,
    imported_by,
    parser_version,
    ok_count,
    warn_count,
    error_count,
    row_count,
    imported_at,
    notes,
    source_hash_sha256
FROM import_batch;

CREATE OR REPLACE VIEW v_importbatchcontractpairing AS
SELECT
    b.batch_id,
    b.filename,
    b.imported_by,
    b.parser_version,
    b.ok_count,
    b.warn_count,
    b.error_count,
    b.row_count,
    b.imported_at,
    b.notes,
    b.source_hash_sha256,
    r.id AS report_id,
    r.source_name,
    r.source_kind,
    r.contract_version,
    r.created_at AS report_created_at,
    r.item_count,
    r.flavour_count,
    r.explicit_relation_count,
    r.raw_prerequisite_count,
    r.missing_target_count,
    r.stub_count,
    r.unresolved_ref_count
FROM v_importbatchsourcehash b
LEFT JOIN v_importcontractreportbyhash r
  ON r.source_hash_sha256 = b.source_hash_sha256
WHERE b.source_hash_sha256 IS NOT NULL;

CREATE OR REPLACE VIEW v_stubcompletionqueue AS
SELECT
    sc.id,
    sc.service_id,
    sc.title,
    sc.service_status_code,
    sc.is_stub,
    sc.notes_json,
    sc.created_at,
    sc.updated_at,
    (
        SELECT COUNT(*)
        FROM data.service_relation sr
        WHERE sr.is_deleted = FALSE
          AND sr.from_service_id = sc.id
    ) AS outgoing_relation_count,
    (
        SELECT COUNT(*)
        FROM data.service_relation sr
        WHERE sr.is_deleted = FALSE
          AND sr.to_service_id = sc.id
    ) AS incoming_relation_count,
    (
        SELECT string_agg(refs.related_service_id, ',')
        FROM (
            SELECT DISTINCT t.service_id AS related_service_id
            FROM data.service_relation sr
            JOIN data.service_catalog t ON t.id = sr.to_service_id
            WHERE sr.is_deleted = FALSE
              AND sr.from_service_id = sc.id
            UNION
            SELECT DISTINCT f.service_id AS related_service_id
            FROM data.service_relation sr
            JOIN data.service_catalog f ON f.id = sr.from_service_id
            WHERE sr.is_deleted = FALSE
              AND sr.to_service_id = sc.id
        ) refs
    ) AS related_service_ids
FROM data.service_catalog sc
WHERE sc.is_deleted = FALSE
  AND sc.is_stub = TRUE
  AND sc.service_status_code = 'external_reference';
