-- =============================================================================
-- SERVICE CATALOGUE — PostgreSQL canonical schema
-- 11_c3.sql | schema: data
-- Converted from backend/db/10_c3taxonomy.sql, 14_c3taxonomy_extended.sql,
-- 17_c3taxonomy_parent.sql, 30_c3_import_entities.sql,
-- 31_c3_entity_reporting.sql, 32_c3_entity_links_exports.sql,
-- 33_c3_capability_builder.sql, 36_c3_capability_builder2.sql,
-- 42_c3_capability_builder_canonical_cleanup.sql,
-- 46_capability_links_completeness_spiral.sql,
-- 47_capability_link_backfill_and_service_publish_readiness.sql,
-- 48_c3_entity_editor_full_views.sql, 49_c3_taxonomy_xlsx_columns.sql
-- =============================================================================

SET search_path TO data, public;

CREATE OR REPLACE FUNCTION parse_seed_timestamptz(p_value TEXT)
RETURNS TIMESTAMPTZ
LANGUAGE sql
IMMUTABLE
AS $$
    SELECT CASE
        WHEN p_value IS NULL OR btrim(p_value) = '' THEN NULL
        ELSE p_value::timestamp AT TIME ZONE 'UTC'
    END
$$;

CREATE TABLE IF NOT EXISTS c3_taxonomy (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid                VARCHAR(100) NOT NULL UNIQUE,
    application         VARCHAR(100) NULL,
    title               VARCHAR(500) NOT NULL,
    description         TEXT NULL,
    source_description  TEXT NULL,
    revised_description TEXT NULL,
    external_id         VARCHAR(200) NULL,
    source_external_id  VARCHAR(200) NULL,
    data_qualifier      VARCHAR(500) NULL,
    data_source         VARCHAR(200) NULL,
    ss_overall_status   VARCHAR(100) NULL,
    ss_baseline_status  VARCHAR(100) NULL,
    item_status         VARCHAR(50) NULL,
    order_num           INTEGER NULL,
    modification_date   TIMESTAMPTZ NULL,
    revised             BOOLEAN NULL DEFAULT FALSE,
    synced_at           TIMESTAMPTZ NULL,
    abbreviation        VARCHAR(200) NULL,
    synonym             TEXT NULL,
    script_raw          TEXT NULL,
    datasets_raw        TEXT NULL,
    standards_raw       TEXT NULL,
    references_raw      TEXT NULL,
    provenance_raw      TEXT NULL,
    item_type           VARCHAR(10) NULL,
    level_num           INTEGER NULL,
    parent_code         VARCHAR(50) NULL,
    parent_uuid         VARCHAR(100) NULL
);

CREATE INDEX IF NOT EXISTS ix_c3_taxonomy_external_id
    ON c3_taxonomy(external_id);

CREATE INDEX IF NOT EXISTS ix_c3_taxonomy_application
    ON c3_taxonomy(application);

CREATE INDEX IF NOT EXISTS ix_c3_taxonomy_parent
    ON c3_taxonomy(parent_uuid)
    INCLUDE (uuid, item_type, title);

CREATE INDEX IF NOT EXISTS ix_c3_taxonomy_item_type
    ON c3_taxonomy(item_type)
    INCLUDE (uuid, external_id, parent_uuid, title, item_status);

CREATE TABLE IF NOT EXISTS c3_application (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_code    VARCHAR(100) NOT NULL,
    uuid                VARCHAR(100) NOT NULL UNIQUE,
    modification_date   TIMESTAMPTZ NULL,
    order_num           INTEGER NULL,
    ss_overall_status   VARCHAR(100) NULL,
    ss_baseline_status  VARCHAR(100) NULL,
    item_status         VARCHAR(50) NULL,
    data_source         VARCHAR(200) NULL,
    external_id         VARCHAR(200) NULL,
    data_qualifier      VARCHAR(500) NULL,
    title               VARCHAR(500) NOT NULL,
    source_description  TEXT NULL,
    revised_description TEXT NULL,
    description         TEXT NULL,
    revised             BOOLEAN NULL DEFAULT FALSE,
    raw_json            TEXT NULL,
    synced_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_c3_application_code
    ON c3_application(application_code);

CREATE TABLE IF NOT EXISTS c3_data_object (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_object_code    VARCHAR(100) NOT NULL,
    uuid                VARCHAR(100) NOT NULL UNIQUE,
    modification_date   TIMESTAMPTZ NULL,
    order_num           INTEGER NULL,
    ss_overall_status   VARCHAR(100) NULL,
    ss_baseline_status  VARCHAR(100) NULL,
    item_status         VARCHAR(50) NULL,
    title               VARCHAR(500) NOT NULL,
    description         TEXT NULL,
    provenance_raw      TEXT NULL,
    references_raw      TEXT NULL,
    standards_raw       TEXT NULL,
    raw_json            TEXT NULL,
    synced_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_c3_data_object_code
    ON c3_data_object(data_object_code);

CREATE TABLE IF NOT EXISTS c3_service (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_code        VARCHAR(100) NOT NULL,
    uuid                VARCHAR(100) NOT NULL UNIQUE,
    modification_date   TIMESTAMPTZ NULL,
    order_num           INTEGER NULL,
    ss_overall_status   VARCHAR(100) NULL,
    ss_baseline_status  VARCHAR(100) NULL,
    item_status         VARCHAR(50) NULL,
    data_source         VARCHAR(200) NULL,
    external_id         VARCHAR(200) NULL,
    data_qualifier      VARCHAR(500) NULL,
    title               VARCHAR(500) NOT NULL,
    source_description  TEXT NULL,
    revised_description TEXT NULL,
    description         TEXT NULL,
    revised             BOOLEAN NULL DEFAULT FALSE,
    raw_json            TEXT NULL,
    synced_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_c3_service_code
    ON c3_service(service_code);

CREATE TABLE IF NOT EXISTS c3_technology_interaction (
    id                               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    technology_interaction_code      VARCHAR(100) NOT NULL,
    uuid                             VARCHAR(100) NOT NULL UNIQUE,
    modification_date                TIMESTAMPTZ NULL,
    order_num                        INTEGER NULL,
    ss_overall_status                VARCHAR(100) NULL,
    ss_baseline_status               VARCHAR(100) NULL,
    item_status                      VARCHAR(50) NULL,
    ciav_review_status               VARCHAR(100) NULL,
    mcsma_review_status              VARCHAR(100) NULL,
    service_instructions             TEXT NULL,
    title                            VARCHAR(500) NOT NULL,
    technology_interaction_type      VARCHAR(200) NULL,
    technology_interaction_maturity  VARCHAR(200) NULL,
    technology_interactions_1_raw    TEXT NULL,
    description                      TEXT NULL,
    conditionality                   TEXT NULL,
    services_1_raw                   TEXT NULL,
    applications_1_raw               TEXT NULL,
    services_2_raw                   TEXT NULL,
    technology_interactions_2_raw    TEXT NULL,
    technology_interactions_3_raw    TEXT NULL,
    services_3_raw                   TEXT NULL,
    applications_2_raw               TEXT NULL,
    data_objects_raw                 TEXT NULL,
    raw_json                         TEXT NULL,
    synced_at                        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at                       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_c3_technology_interaction_code
    ON c3_technology_interaction(technology_interaction_code);

CREATE TABLE IF NOT EXISTS c3_entity_import_run (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_key      VARCHAR(100) NOT NULL,
    source_name     VARCHAR(500) NULL,
    source_kind     VARCHAR(20) NOT NULL,
    is_dry_run      BOOLEAN NOT NULL DEFAULT FALSE,
    row_count       INTEGER NOT NULL DEFAULT 0,
    ok_count        INTEGER NOT NULL DEFAULT 0,
    warn_count      INTEGER NOT NULL DEFAULT 0,
    error_count     INTEGER NOT NULL DEFAULT 0,
    inserted_count  INTEGER NOT NULL DEFAULT 0,
    updated_count   INTEGER NOT NULL DEFAULT 0,
    failed_count    INTEGER NOT NULL DEFAULT 0,
    created_by      VARCHAR(255) NULL,
    notes           TEXT NULL,
    spiral_code     VARCHAR(20) NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS c3_entity_import_issue (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id       BIGINT NOT NULL REFERENCES c3_entity_import_run(id) ON DELETE CASCADE,
    row_number   INTEGER NULL,
    severity     VARCHAR(20) NOT NULL,
    issue_code   VARCHAR(100) NOT NULL,
    field_name   VARCHAR(100) NULL,
    raw_value    TEXT NULL,
    message      TEXT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_c3_entity_import_run_target_created
    ON c3_entity_import_run(target_key, is_dry_run, created_at DESC);

CREATE INDEX IF NOT EXISTS ix_c3_entity_import_issue_run
    ON c3_entity_import_issue(run_id, row_number);

CREATE TABLE IF NOT EXISTS c3_technology_interaction_service_link (
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    technology_interaction_id  BIGINT NOT NULL REFERENCES c3_technology_interaction(id) ON DELETE CASCADE,
    c3_service_id              BIGINT NOT NULL REFERENCES c3_service(id) ON DELETE CASCADE,
    source_slot                VARCHAR(50) NOT NULL,
    ref_value                  VARCHAR(200) NULL,
    created_at                 TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_c3_ti_service_link_ti
    ON c3_technology_interaction_service_link(technology_interaction_id, source_slot);

CREATE TABLE IF NOT EXISTS c3_technology_interaction_application_link (
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    technology_interaction_id  BIGINT NOT NULL REFERENCES c3_technology_interaction(id) ON DELETE CASCADE,
    c3_application_id          BIGINT NOT NULL REFERENCES c3_application(id) ON DELETE CASCADE,
    source_slot                VARCHAR(50) NOT NULL,
    ref_value                  VARCHAR(200) NULL,
    created_at                 TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_c3_ti_application_link_ti
    ON c3_technology_interaction_application_link(technology_interaction_id, source_slot);

CREATE TABLE IF NOT EXISTS c3_technology_interaction_data_object_link (
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    technology_interaction_id  BIGINT NOT NULL REFERENCES c3_technology_interaction(id) ON DELETE CASCADE,
    c3_data_object_id          BIGINT NOT NULL REFERENCES c3_data_object(id) ON DELETE CASCADE,
    source_slot                VARCHAR(50) NOT NULL,
    ref_value                  VARCHAR(200) NULL,
    created_at                 TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_c3_ti_data_object_link_ti
    ON c3_technology_interaction_data_object_link(technology_interaction_id, source_slot);

CREATE TABLE IF NOT EXISTS c3_entity_seed_snapshot_state (
    seed_key    VARCHAR(100) PRIMARY KEY,
    seed_source VARCHAR(400) NULL,
    seeded_at   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ref_c3_capability_domain (
    code              VARCHAR(100) PRIMARY KEY,
    css_class         VARCHAR(50) NOT NULL,
    heading_color     VARCHAR(20) NOT NULL,
    background_color  VARCHAR(20) NOT NULL,
    label             VARCHAR(200) NOT NULL,
    sort_order        INTEGER NOT NULL,
    is_active         BOOLEAN NOT NULL DEFAULT TRUE,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS c3_capability_builder (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    page_id      VARCHAR(100) NOT NULL UNIQUE,
    uuid         VARCHAR(100) NOT NULL UNIQUE,
    title        VARCHAR(500) NOT NULL,
    parent_id    VARCHAR(100) NULL,
    level        INTEGER NOT NULL CHECK (level BETWEEN 1 AND 20),
    state        VARCHAR(50) NULL,
    domain_code  VARCHAR(100) NOT NULL REFERENCES ref_c3_capability_domain(code),
    created_at   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_c3_capability_builder_domain_level_parent
    ON c3_capability_builder(domain_code, level, parent_id)
    INCLUDE (page_id, title, state);

CREATE INDEX IF NOT EXISTS ix_c3_capability_builder_parent
    ON c3_capability_builder(parent_id)
    INCLUDE (page_id, title, level, domain_code);

CREATE TABLE IF NOT EXISTS c3_capability_builder_seed_state (
    seed_version VARCHAR(100) PRIMARY KEY,
    seed_source  VARCHAR(400) NULL,
    seeded_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS c3_capability_application_link (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    capability_uuid    VARCHAR(100) NOT NULL REFERENCES c3_taxonomy(uuid) ON DELETE CASCADE,
    c3_application_id  BIGINT NOT NULL REFERENCES c3_application(id) ON DELETE CASCADE,
    link_role          VARCHAR(50) NULL,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by         VARCHAR(255) NULL,
    CONSTRAINT uq_c3_capability_application_link UNIQUE (capability_uuid, c3_application_id)
);

CREATE INDEX IF NOT EXISTS ix_c3_capability_application_link_cap
    ON c3_capability_application_link(capability_uuid);

CREATE INDEX IF NOT EXISTS ix_c3_capability_application_link_app
    ON c3_capability_application_link(c3_application_id);

CREATE TABLE IF NOT EXISTS c3_capability_data_object_link (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    capability_uuid    VARCHAR(100) NOT NULL REFERENCES c3_taxonomy(uuid) ON DELETE CASCADE,
    c3_data_object_id  BIGINT NOT NULL REFERENCES c3_data_object(id) ON DELETE CASCADE,
    link_role          VARCHAR(50) NULL,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by         VARCHAR(255) NULL,
    CONSTRAINT uq_c3_capability_data_object_link UNIQUE (capability_uuid, c3_data_object_id)
);

CREATE INDEX IF NOT EXISTS ix_c3_capability_data_object_link_cap
    ON c3_capability_data_object_link(capability_uuid);

CREATE INDEX IF NOT EXISTS ix_c3_capability_data_object_link_data_object
    ON c3_capability_data_object_link(c3_data_object_id);

CREATE TABLE IF NOT EXISTS c3_capability_tin_link (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    capability_uuid  VARCHAR(100) NOT NULL REFERENCES c3_taxonomy(uuid) ON DELETE CASCADE,
    c3_tin_id        BIGINT NOT NULL REFERENCES c3_technology_interaction(id) ON DELETE CASCADE,
    link_role        VARCHAR(50) NULL,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by       VARCHAR(255) NULL,
    CONSTRAINT uq_c3_capability_tin_link UNIQUE (capability_uuid, c3_tin_id)
);

CREATE INDEX IF NOT EXISTS ix_c3_capability_tin_link_cap
    ON c3_capability_tin_link(capability_uuid);

CREATE INDEX IF NOT EXISTS ix_c3_capability_tin_link_tin
    ON c3_capability_tin_link(c3_tin_id);

CREATE TABLE IF NOT EXISTS c3_capability_c3_service_link (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    capability_uuid  VARCHAR(100) NOT NULL REFERENCES c3_taxonomy(uuid) ON DELETE CASCADE,
    c3_service_id    BIGINT NOT NULL REFERENCES c3_service(id) ON DELETE CASCADE,
    link_role        VARCHAR(50) NULL,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by       VARCHAR(255) NULL,
    CONSTRAINT uq_c3_capability_c3_service_link UNIQUE (capability_uuid, c3_service_id)
);

CREATE INDEX IF NOT EXISTS ix_c3_capability_c3_service_link_cap
    ON c3_capability_c3_service_link(capability_uuid);

CREATE INDEX IF NOT EXISTS ix_c3_capability_c3_service_link_service
    ON c3_capability_c3_service_link(c3_service_id);

CREATE TABLE IF NOT EXISTS ref_spiral_baseline (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    spiral_code   VARCHAR(20) NOT NULL UNIQUE,
    spiral_label  VARCHAR(100) NOT NULL,
    is_active     BOOLEAN NOT NULL DEFAULT FALSE,
    notes         TEXT NULL,
    activated_at  TIMESTAMPTZ NULL,
    activated_by  VARCHAR(255) NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO ref_spiral_baseline (
    spiral_code,
    spiral_label,
    is_active,
    notes,
    activated_at
)
VALUES (
    'Spiral_6',
    'Spiral 6 (current baseline)',
    TRUE,
    'Import completed according to Spiral 6; includes all C3 entities as of activation date.',
    CURRENT_TIMESTAMP
)
ON CONFLICT (spiral_code) DO UPDATE SET
    spiral_label = EXCLUDED.spiral_label,
    is_active = EXCLUDED.is_active,
    notes = EXCLUDED.notes,
    activated_at = EXCLUDED.activated_at;

CREATE OR REPLACE VIEW v_c3applicationlist AS
SELECT
    id,
    application_code,
    uuid,
    modification_date,
    order_num,
    ss_overall_status,
    ss_baseline_status,
    item_status,
    data_source,
    external_id,
    data_qualifier,
    title,
    source_description,
    revised_description,
    description,
    revised,
    synced_at,
    updated_at
FROM c3_application;

CREATE OR REPLACE VIEW v_c3dataobjectlist AS
SELECT
    id,
    data_object_code,
    uuid,
    modification_date,
    order_num,
    ss_overall_status,
    ss_baseline_status,
    item_status,
    title,
    description,
    provenance_raw,
    references_raw,
    standards_raw,
    synced_at,
    updated_at
FROM c3_data_object;

CREATE OR REPLACE VIEW v_c3servicelist AS
SELECT
    id,
    service_code,
    uuid,
    modification_date,
    order_num,
    ss_overall_status,
    ss_baseline_status,
    item_status,
    data_source,
    external_id,
    data_qualifier,
    title,
    source_description,
    revised_description,
    description,
    revised,
    synced_at,
    updated_at
FROM c3_service;

CREATE OR REPLACE VIEW v_c3technologyinteractionlinkreport AS
WITH service_raw AS (
    SELECT ti.id, btrim(value) AS ref_value
    FROM c3_technology_interaction ti
    CROSS JOIN LATERAL regexp_split_to_table(
        regexp_replace(concat_ws(',', ti.services_1_raw, ti.services_2_raw, ti.services_3_raw), E'[\\r\\n;]+', ',', 'g'),
        ','
    ) AS value
    WHERE btrim(value) <> ''
),
application_raw AS (
    SELECT ti.id, btrim(value) AS ref_value
    FROM c3_technology_interaction ti
    CROSS JOIN LATERAL regexp_split_to_table(
        regexp_replace(concat_ws(',', ti.applications_1_raw, ti.applications_2_raw), E'[\\r\\n;]+', ',', 'g'),
        ','
    ) AS value
    WHERE btrim(value) <> ''
),
data_object_raw AS (
    SELECT ti.id, btrim(value) AS ref_value
    FROM c3_technology_interaction ti
    CROSS JOIN LATERAL regexp_split_to_table(
        regexp_replace(coalesce(ti.data_objects_raw, ''), E'[\\r\\n;]+', ',', 'g'),
        ','
    ) AS value
    WHERE btrim(value) <> ''
),
service_agg AS (
    SELECT
        r.id,
        COUNT(*) AS service_ref_count,
        COUNT(s.id) AS matched_service_count,
        string_agg(CASE WHEN s.id IS NULL THEN r.ref_value END, ', ' ORDER BY r.ref_value) AS unresolved_service_refs
    FROM service_raw r
    LEFT JOIN c3_service s
      ON s.service_code = r.ref_value OR s.uuid = r.ref_value
    GROUP BY r.id
),
application_agg AS (
    SELECT
        r.id,
        COUNT(*) AS application_ref_count,
        COUNT(a.id) AS matched_application_count,
        string_agg(CASE WHEN a.id IS NULL THEN r.ref_value END, ', ' ORDER BY r.ref_value) AS unresolved_application_refs
    FROM application_raw r
    LEFT JOIN c3_application a
      ON a.application_code = r.ref_value OR a.uuid = r.ref_value
    GROUP BY r.id
),
data_object_agg AS (
    SELECT
        r.id,
        COUNT(*) AS data_object_ref_count,
        COUNT(d.id) AS matched_data_object_count,
        string_agg(CASE WHEN d.id IS NULL THEN r.ref_value END, ', ' ORDER BY r.ref_value) AS unresolved_data_object_refs
    FROM data_object_raw r
    LEFT JOIN c3_data_object d
      ON d.data_object_code = r.ref_value OR d.uuid = r.ref_value
    GROUP BY r.id
),
service_links AS (
    SELECT
        l.technology_interaction_id AS id,
        jsonb_agg(
            jsonb_build_object('id', s.id, 'code', s.service_code, 'uuid', s.uuid, 'title', s.title)
            ORDER BY s.service_code
        )::text AS linked_services_json
    FROM c3_technology_interaction_service_link l
    JOIN c3_service s ON s.id = l.c3_service_id
    GROUP BY l.technology_interaction_id
),
application_links AS (
    SELECT
        l.technology_interaction_id AS id,
        jsonb_agg(
            jsonb_build_object('id', a.id, 'code', a.application_code, 'uuid', a.uuid, 'title', a.title)
            ORDER BY a.application_code
        )::text AS linked_applications_json
    FROM c3_technology_interaction_application_link l
    JOIN c3_application a ON a.id = l.c3_application_id
    GROUP BY l.technology_interaction_id
),
data_object_links AS (
    SELECT
        l.technology_interaction_id AS id,
        jsonb_agg(
            jsonb_build_object('id', d.id, 'code', d.data_object_code, 'uuid', d.uuid, 'title', d.title)
            ORDER BY d.data_object_code
        )::text AS linked_data_objects_json
    FROM c3_technology_interaction_data_object_link l
    JOIN c3_data_object d ON d.id = l.c3_data_object_id
    GROUP BY l.technology_interaction_id
)
SELECT
    ti.id,
    ti.technology_interaction_code,
    ti.uuid,
    ti.title,
    ti.item_status,
    ti.technology_interaction_type,
    ti.technology_interaction_maturity,
    COALESCE(sa.service_ref_count, 0) AS service_ref_count,
    COALESCE(sa.matched_service_count, 0) AS matched_service_count,
    sl.linked_services_json,
    sa.unresolved_service_refs,
    COALESCE(aa.application_ref_count, 0) AS application_ref_count,
    COALESCE(aa.matched_application_count, 0) AS matched_application_count,
    al.linked_applications_json,
    aa.unresolved_application_refs,
    COALESCE(da.data_object_ref_count, 0) AS data_object_ref_count,
    COALESCE(da.matched_data_object_count, 0) AS matched_data_object_count,
    dl.linked_data_objects_json,
    da.unresolved_data_object_refs,
    ti.synced_at,
    ti.updated_at
FROM c3_technology_interaction ti
LEFT JOIN service_agg sa ON sa.id = ti.id
LEFT JOIN service_links sl ON sl.id = ti.id
LEFT JOIN application_agg aa ON aa.id = ti.id
LEFT JOIN application_links al ON al.id = ti.id
LEFT JOIN data_object_agg da ON da.id = ti.id
LEFT JOIN data_object_links dl ON dl.id = ti.id;

CREATE OR REPLACE VIEW v_c3technologyinteractionlist AS
SELECT
    ti.id,
    ti.technology_interaction_code,
    ti.uuid,
    ti.modification_date,
    ti.order_num,
    ti.ss_overall_status,
    ti.ss_baseline_status,
    ti.item_status,
    ti.ciav_review_status,
    ti.mcsma_review_status,
    ti.service_instructions,
    ti.title,
    ti.technology_interaction_type,
    ti.technology_interaction_maturity,
    ti.technology_interactions_1_raw,
    ti.description,
    ti.conditionality,
    ti.services_1_raw,
    ti.applications_1_raw,
    ti.services_2_raw,
    ti.technology_interactions_2_raw,
    ti.technology_interactions_3_raw,
    ti.services_3_raw,
    ti.applications_2_raw,
    ti.data_objects_raw,
    lr.matched_service_count,
    lr.matched_application_count,
    lr.matched_data_object_count,
    lr.linked_services_json,
    lr.linked_applications_json,
    lr.linked_data_objects_json,
    lr.unresolved_service_refs,
    lr.unresolved_application_refs,
    lr.unresolved_data_object_refs,
    ti.synced_at,
    ti.updated_at
FROM c3_technology_interaction ti
LEFT JOIN v_c3technologyinteractionlinkreport lr
  ON lr.id = ti.id;

CREATE OR REPLACE VIEW v_c3capabilitybuilderdomain AS
SELECT
    code,
    css_class,
    heading_color,
    background_color,
    label,
    sort_order,
    is_active
FROM ref_c3_capability_domain
WHERE is_active = TRUE;

CREATE OR REPLACE VIEW v_c3capabilitybuilderlist AS
SELECT
    b.id,
    b.page_id,
    b.uuid,
    b.title,
    b.parent_id,
    parent.title AS parent_title,
    b.level,
    b.state,
    b.domain_code,
    d.css_class,
    d.heading_color,
    d.background_color,
    d.label AS domain_label,
    d.sort_order AS domain_order,
    b.created_at,
    b.updated_at
FROM c3_capability_builder b
JOIN ref_c3_capability_domain d
  ON d.code = b.domain_code
LEFT JOIN c3_capability_builder parent
  ON parent.page_id = b.parent_id
WHERE d.is_active = TRUE;

CREATE OR REPLACE VIEW v_c3capabilitycompleteness AS
SELECT
    c.uuid,
    c.external_id,
    c.title,
    c.item_type,
    c.item_status,
    COALESCE(app.cnt, 0) AS app_count,
    COALESCE(do_.cnt, 0) AS data_object_count,
    COALESCE(tin.cnt, 0) AS tin_count,
    COALESCE(svc.cnt, 0) AS c3_service_count,
    COALESCE(scm.cnt, 0) AS service_mapping_count,
    CASE WHEN COALESCE(app.cnt, 0) > 0 THEN TRUE ELSE FALSE END AS has_app,
    CASE WHEN COALESCE(do_.cnt, 0) > 0 THEN TRUE ELSE FALSE END AS has_data_object,
    CASE WHEN COALESCE(tin.cnt, 0) > 0 THEN TRUE ELSE FALSE END AS has_tin,
    CASE WHEN COALESCE(svc.cnt, 0) > 0 THEN TRUE ELSE FALSE END AS has_c3_service,
    CASE WHEN COALESCE(scm.cnt, 0) > 0 THEN TRUE ELSE FALSE END AS has_service_mapping,
    CASE
        WHEN COALESCE(app.cnt, 0) > 0
         AND COALESCE(do_.cnt, 0) > 0
         AND COALESCE(tin.cnt, 0) > 0 THEN 'complete'
        WHEN COALESCE(app.cnt, 0)
           + COALESCE(do_.cnt, 0)
           + COALESCE(tin.cnt, 0)
           + COALESCE(svc.cnt, 0)
           + COALESCE(scm.cnt, 0) > 0 THEN 'partial'
        ELSE 'incomplete'
    END AS completeness_status
FROM c3_taxonomy c
LEFT JOIN (
    SELECT capability_uuid, COUNT(*) AS cnt
    FROM c3_capability_application_link
    GROUP BY capability_uuid
) app ON app.capability_uuid = c.uuid
LEFT JOIN (
    SELECT capability_uuid, COUNT(*) AS cnt
    FROM c3_capability_data_object_link
    GROUP BY capability_uuid
) do_ ON do_.capability_uuid = c.uuid
LEFT JOIN (
    SELECT capability_uuid, COUNT(*) AS cnt
    FROM c3_capability_tin_link
    GROUP BY capability_uuid
) tin ON tin.capability_uuid = c.uuid
LEFT JOIN (
    SELECT capability_uuid, COUNT(*) AS cnt
    FROM c3_capability_c3_service_link
    GROUP BY capability_uuid
) svc ON svc.capability_uuid = c.uuid
LEFT JOIN (
    SELECT c3_uuid, COUNT(*) AS cnt
    FROM service_c3_mapping
    GROUP BY c3_uuid
) scm ON scm.c3_uuid = c.uuid;

CREATE OR REPLACE VIEW v_servicepublishreadiness AS
WITH active_flavours AS (
    SELECT
        sf.service_id,
        COUNT(*) AS active_flavour_count
    FROM service_flavour sf
    WHERE sf.is_deleted = FALSE
      AND lower(COALESCE(sf.flavour_status_code, '')) IN ('available', 'active')
    GROUP BY sf.service_id
),
relation_counts AS (
    SELECT
        sc.id AS service_id,
        COUNT(sr.id) AS relation_count,
        SUM(CASE WHEN sr.relation_type_code IN ('depends_on', 'prerequisite', 'underlying') THEN 1 ELSE 0 END) AS dependency_relation_count
    FROM service_catalog sc
    LEFT JOIN service_relation sr
      ON sr.is_deleted = FALSE
     AND (sr.from_service_id = sc.id OR sr.to_service_id = sc.id)
    WHERE sc.is_deleted = FALSE
    GROUP BY sc.id
),
primary_mapping AS (
    SELECT
        scm.service_id,
        COUNT(*) AS primary_mapping_count,
        MAX(CASE WHEN scm.is_primary = TRUE THEN scm.c3_uuid END) AS primary_c3_uuid
    FROM service_c3_mapping scm
    JOIN service_catalog sc
      ON sc.id = scm.service_id
     AND sc.is_deleted = FALSE
    WHERE scm.is_primary = TRUE
    GROUP BY scm.service_id
)
SELECT
    sc.id AS service_pk,
    sc.service_id,
    sc.title,
    sc.service_status_code AS service_status,
    pm.primary_mapping_count,
    pm.primary_c3_uuid,
    cap.title AS primary_c3_title,
    cap.external_id AS primary_c3_code,
    comp.completeness_status AS primary_c3_completeness_status,
    comp.app_count AS primary_c3_app_count,
    comp.data_object_count AS primary_c3_data_object_count,
    comp.tin_count AS primary_c3_tin_count,
    comp.c3_service_count AS primary_c3_c3_service_count,
    comp.service_mapping_count AS primary_c3_service_mapping_count,
    COALESCE(af.active_flavour_count, 0) AS active_flavour_count,
    COALESCE(rc.relation_count, 0) AS relation_count,
    COALESCE(rc.dependency_relation_count, 0) AS dependency_relation_count,
    CASE WHEN COALESCE(pm.primary_mapping_count, 0) = 1 AND pm.primary_c3_uuid IS NOT NULL THEN TRUE ELSE FALSE END AS has_single_primary_mapping,
    CASE WHEN comp.completeness_status = 'complete' THEN TRUE ELSE FALSE END AS has_complete_primary_capability,
    CASE WHEN COALESCE(af.active_flavour_count, 0) > 0 THEN TRUE ELSE FALSE END AS has_active_flavour,
    CASE
        WHEN COALESCE(pm.primary_mapping_count, 0) = 1
         AND pm.primary_c3_uuid IS NOT NULL
         AND comp.completeness_status = 'complete'
         AND COALESCE(af.active_flavour_count, 0) > 0
        THEN TRUE ELSE FALSE
    END AS is_publishable
FROM service_catalog sc
LEFT JOIN primary_mapping pm
  ON pm.service_id = sc.id
LEFT JOIN c3_taxonomy cap
  ON cap.uuid = pm.primary_c3_uuid
LEFT JOIN v_c3capabilitycompleteness comp
  ON comp.uuid = pm.primary_c3_uuid
LEFT JOIN active_flavours af
  ON af.service_id = sc.id
LEFT JOIN relation_counts rc
  ON rc.service_id = sc.id
WHERE sc.is_deleted = FALSE
  AND sc.is_stub = FALSE;

CREATE OR REPLACE VIEW v_c3dashboardsummary AS
WITH mapped AS (
    SELECT DISTINCT c3_uuid
    FROM service_c3_mapping
    WHERE c3_uuid IS NOT NULL
),
mapping_counts AS (
    SELECT c3_uuid, COUNT(*) AS mapping_count
    FROM service_c3_mapping
    WHERE c3_uuid IS NOT NULL
    GROUP BY c3_uuid
)
SELECT
    COUNT(*) AS total_items,
    SUM(CASE WHEN m.c3_uuid IS NOT NULL THEN 1 ELSE 0 END) AS mapped_items,
    SUM(CASE WHEN m.c3_uuid IS NULL THEN 1 ELSE 0 END) AS unmapped_items,
    COALESCE(SUM(mc.mapping_count), 0) AS total_mappings,
    COUNT(DISTINCT c.item_type) AS item_type_count,
    COUNT(DISTINCT c.application) AS application_count
FROM c3_taxonomy c
LEFT JOIN mapped m
  ON m.c3_uuid = c.uuid
LEFT JOIN mapping_counts mc
  ON mc.c3_uuid = c.uuid;

CREATE OR REPLACE VIEW v_c3entityimportrunlatest AS
WITH ranked AS (
    SELECT
        id,
        target_key,
        source_name,
        source_kind,
        is_dry_run,
        row_count,
        ok_count,
        warn_count,
        error_count,
        inserted_count,
        updated_count,
        failed_count,
        created_by,
        notes,
        spiral_code,
        created_at,
        ROW_NUMBER() OVER (PARTITION BY target_key ORDER BY created_at DESC, id DESC) AS rn
    FROM c3_entity_import_run
    WHERE is_dry_run = FALSE
)
SELECT
    id,
    target_key,
    source_name,
    source_kind,
    is_dry_run,
    row_count,
    ok_count,
    warn_count,
    error_count,
    inserted_count,
    updated_count,
    failed_count,
    created_by,
    notes,
    spiral_code,
    created_at
FROM ranked
WHERE rn = 1;

CREATE OR REPLACE VIEW v_c3applicationexport AS
SELECT * FROM c3_application;

CREATE OR REPLACE VIEW v_c3dataobjectexport AS
SELECT * FROM c3_data_object;

CREATE OR REPLACE VIEW v_c3serviceexport AS
SELECT * FROM c3_service;

CREATE OR REPLACE VIEW v_c3technologyinteractionexport AS
SELECT * FROM c3_technology_interaction;

CREATE OR REPLACE VIEW v_c3technologyinteractionservicelinkexport AS
SELECT * FROM c3_technology_interaction_service_link;

CREATE OR REPLACE VIEW v_c3technologyinteractionapplicationlinkexport AS
SELECT * FROM c3_technology_interaction_application_link;

CREATE OR REPLACE VIEW v_c3technologyinteractiondataobjectlinkexport AS
SELECT * FROM c3_technology_interaction_data_object_link;

CREATE OR REPLACE VIEW v_c3capabilityapplicationlinkexport AS
SELECT * FROM c3_capability_application_link;

CREATE OR REPLACE VIEW v_c3capabilitydataobjectlinkexport AS
SELECT * FROM c3_capability_data_object_link;

CREATE OR REPLACE VIEW v_c3capabilitytinlinkexport AS
SELECT * FROM c3_capability_tin_link;

CREATE OR REPLACE VIEW v_c3capabilityc3servicelinkexport AS
SELECT * FROM c3_capability_c3_service_link;

CREATE OR REPLACE VIEW v_c3entityimportrunexport AS
SELECT * FROM c3_entity_import_run;

CREATE OR REPLACE VIEW v_c3entityimportissueexport AS
SELECT * FROM c3_entity_import_issue;
