-- =============================================================================
-- SERVICE CATALOGUE — PostgreSQL canonical schema
-- 12_exports_retention.sql | schemas: platform, data
-- Converted from backend/db/21_canonical_routes_exports_audit.sql
--                 + backend/db/22_c3_dashboard_capability_map.sql
--                 + backend/db/23_export_manifest_import_audit.sql
--                 + backend/db/24_production_readiness.sql
-- =============================================================================

SET search_path TO platform, public;

CREATE TABLE IF NOT EXISTS canonical_route_metadata (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_key         VARCHAR(100) NOT NULL UNIQUE,
    feature_area      VARCHAR(100) NOT NULL,
    canonical_path    VARCHAR(255) NOT NULL UNIQUE,
    legacy_paths_json TEXT NULL,
    route_kind        VARCHAR(30) NOT NULL,
    export_endpoint   VARCHAR(255) NULL,
    is_active         BOOLEAN NOT NULL DEFAULT TRUE,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO canonical_route_metadata (
    route_key,
    feature_area,
    canonical_path,
    legacy_paths_json,
    route_kind,
    export_endpoint,
    is_active
)
VALUES
    ('c3.list', 'c3', '/c3/list', '["/admin/c3"]', 'page', '/api/v1/export/taxonomy', TRUE),
    ('c3.dashboard', 'c3', '/c3/dashboard', '["/admin/c3/dashboard"]', 'page', '/api/v1/export/taxonomy', TRUE),
    ('c3.capability_map', 'c3', '/c3/capability-map', '["/c3-dashboard"]', 'page', '/api/v1/export/capability-map-hierarchy', TRUE),
    ('c3.detail', 'c3', '/c3/{uuid}', '["/admin/c3/{uuid}"]', 'page', '/api/v1/export/capability-map-hierarchy', TRUE),
    ('c3.graph', 'c3', '/c3/graph', '["/admin/c3/graph"]', 'page', '/api/v1/export/c3-relationships', TRUE),
    ('services.list', 'service', '/services/list', '["/"]', 'page', NULL, TRUE),
    ('services.dashboard', 'service', '/services/dashboard', NULL, 'page', NULL, TRUE),
    ('services.graph', 'service', '/services/graph', NULL, 'page', '/api/v1/export/graph-overview', TRUE),
    ('pricing.ui', 'pricing', '/services/{id}/edit#flavours', NULL, 'page', '/api/v1/export/pricing', TRUE),
    ('sla.ui', 'sla', '/services/{id}/edit#sla', NULL, 'page', '/api/v1/export/sla', TRUE),
    ('export.taxonomy', 'export', '/api/v1/export/taxonomy', NULL, 'api', '/api/v1/export/taxonomy', TRUE),
    ('export.graph', 'export', '/api/v1/export/graph-overview', NULL, 'api', '/api/v1/export/graph-overview', TRUE),
    ('export.pricing', 'export', '/api/v1/export/pricing', NULL, 'api', '/api/v1/export/pricing', TRUE),
    ('export.sla', 'export', '/api/v1/export/sla', NULL, 'api', '/api/v1/export/sla', TRUE),
    ('export.bundle', 'export', '/api/v1/export/bundle', NULL, 'api', '/api/v1/export/bundle', TRUE),
    ('export.manifest', 'export', '/api/v1/export/manifest', NULL, 'api', '/api/v1/export/manifest', TRUE),
    ('export.c3_relationships', 'export', '/api/v1/export/c3-relationships', NULL, 'api', '/api/v1/export/c3-relationships', TRUE),
    ('export.capability_map', 'export', '/api/v1/export/capability-map-hierarchy', NULL, 'api', '/api/v1/export/capability-map-hierarchy', TRUE),
    ('import.review', 'import', '/import', NULL, 'page', '/api/v1/export/bundle', TRUE),
    ('import.admin_review', 'import', '/admin/import', NULL, 'page', '/api/v1/export/bundle', TRUE),
    ('import.upload', 'import', '/import/upload', NULL, 'page', '/api/v1/export/bundle', TRUE)
ON CONFLICT (route_key) DO UPDATE SET
    feature_area = EXCLUDED.feature_area,
    canonical_path = EXCLUDED.canonical_path,
    legacy_paths_json = EXCLUDED.legacy_paths_json,
    route_kind = EXCLUDED.route_kind,
    export_endpoint = EXCLUDED.export_endpoint,
    is_active = EXCLUDED.is_active,
    updated_at = CURRENT_TIMESTAMP;

CREATE OR REPLACE VIEW v_canonical_route_metadata AS
SELECT
    route_key,
    feature_area,
    canonical_path,
    legacy_paths_json,
    route_kind,
    export_endpoint
FROM canonical_route_metadata
WHERE is_active = TRUE;

CREATE TABLE IF NOT EXISTS export_bundle_metadata (
    bundle_key         VARCHAR(100) PRIMARY KEY,
    contract_version   VARCHAR(50) NOT NULL,
    schema_version     VARCHAR(50) NOT NULL,
    retention_days     INTEGER NULL,
    archive_after_days INTEGER NULL,
    notes              TEXT NULL,
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO export_bundle_metadata (
    bundle_key,
    contract_version,
    schema_version,
    retention_days,
    archive_after_days,
    notes
)
VALUES (
    'service_catalog_bundle',
    '2026-03-30.c3-v3',
    'canonical-23',
    365,
    90,
    'Service graph + pricing + SLA + taxonomy + import/audit exports'
)
ON CONFLICT (bundle_key) DO UPDATE SET
    contract_version = EXCLUDED.contract_version,
    schema_version = EXCLUDED.schema_version,
    retention_days = EXCLUDED.retention_days,
    archive_after_days = EXCLUDED.archive_after_days,
    notes = EXCLUDED.notes,
    updated_at = CURRENT_TIMESTAMP;

CREATE OR REPLACE VIEW v_export_bundle_manifest AS
SELECT
    ebm.bundle_key,
    ebm.contract_version,
    ebm.schema_version,
    ebm.retention_days,
    ebm.archive_after_days,
    ebm.notes,
    ebm.updated_at,
    (
        SELECT COUNT(*)
        FROM platform.v_canonical_route_metadata crm
        WHERE crm.feature_area = 'export'
    ) AS export_route_count
FROM export_bundle_metadata ebm;

CREATE TABLE IF NOT EXISTS export_bundle_audit (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bundle_key         VARCHAR(100) NOT NULL,
    contract_version   VARCHAR(50) NOT NULL,
    schema_version     VARCHAR(50) NOT NULL,
    requested_by       VARCHAR(200) NOT NULL,
    requested_ip       VARCHAR(100) NULL,
    record_counts_json TEXT NOT NULL,
    generated_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE VIEW v_export_bundle_audit AS
SELECT
    id,
    bundle_key,
    contract_version,
    schema_version,
    requested_by,
    requested_ip,
    record_counts_json,
    generated_at
FROM export_bundle_audit;

SET search_path TO data, public;

CREATE TABLE IF NOT EXISTS audit_retention_policy (
    policy_key         VARCHAR(100) PRIMARY KEY,
    target_table       VARCHAR(128) NOT NULL,
    retention_days     INTEGER NOT NULL,
    archive_after_days INTEGER NULL,
    is_active          BOOLEAN NOT NULL DEFAULT TRUE,
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS retention_job_audit (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trigger_source         VARCHAR(100) NOT NULL,
    status                 VARCHAR(20) NOT NULL,
    deleted_import_issue   INTEGER NOT NULL DEFAULT 0,
    deleted_import_row     INTEGER NOT NULL DEFAULT 0,
    deleted_import_batch   INTEGER NOT NULL DEFAULT 0,
    deleted_taxonomy_audit INTEGER NOT NULL DEFAULT 0,
    deleted_graph_audit    INTEGER NOT NULL DEFAULT 0,
    started_at             TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at           TIMESTAMPTZ NULL,
    error_message          TEXT NULL
);

CREATE TABLE IF NOT EXISTS retention_runner_heartbeat (
    runner_name           VARCHAR(120) PRIMARY KEY,
    runner_kind           VARCHAR(50) NOT NULL DEFAULT 'docker-service',
    status                VARCHAR(20) NOT NULL DEFAULT 'unknown',
    last_seen_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_run_started_at   TIMESTAMPTZ NULL,
    last_run_completed_at TIMESTAMPTZ NULL,
    last_job_status       VARCHAR(20) NULL,
    last_error_message    TEXT NULL,
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO audit_retention_policy (
    policy_key,
    target_table,
    retention_days,
    archive_after_days,
    is_active
)
VALUES
    ('taxonomy_mapping_audit', 'data.taxonomy_mapping_audit', 365, 90, TRUE),
    ('graph_layout_audit', 'data.graph_layout_audit', 365, 90, TRUE),
    ('import_batch', 'data.import_batch', 365, 90, TRUE),
    ('import_row', 'data.import_row', 180, 60, TRUE),
    ('import_issue', 'data.import_issue', 365, 90, TRUE)
ON CONFLICT (policy_key) DO UPDATE SET
    target_table = EXCLUDED.target_table,
    retention_days = EXCLUDED.retention_days,
    archive_after_days = EXCLUDED.archive_after_days,
    is_active = EXCLUDED.is_active,
    updated_at = CURRENT_TIMESTAMP;

CREATE OR REPLACE VIEW v_auditretentionpolicy AS
SELECT
    policy_key,
    target_table,
    retention_days,
    archive_after_days,
    is_active,
    updated_at
FROM audit_retention_policy
WHERE is_active = TRUE;

CREATE OR REPLACE VIEW v_retentionjobauditexport AS
SELECT * FROM retention_job_audit;

CREATE OR REPLACE VIEW v_retentionrunnerheartbeat AS
SELECT * FROM retention_runner_heartbeat;

CREATE OR REPLACE FUNCTION upsert_retention_runner_heartbeat(
    p_runner_name VARCHAR(120),
    p_runner_kind VARCHAR(50) DEFAULT 'app-inline',
    p_status VARCHAR(20) DEFAULT 'idle',
    p_last_run_started_at TIMESTAMPTZ DEFAULT NULL,
    p_last_run_completed_at TIMESTAMPTZ DEFAULT NULL,
    p_last_job_status VARCHAR(20) DEFAULT NULL,
    p_last_error_message TEXT DEFAULT NULL
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO retention_runner_heartbeat (
        runner_name,
        runner_kind,
        status,
        last_seen_at,
        last_run_started_at,
        last_run_completed_at,
        last_job_status,
        last_error_message,
        updated_at
    )
    VALUES (
        p_runner_name,
        COALESCE(NULLIF(p_runner_kind, ''), 'app-inline'),
        COALESCE(NULLIF(p_status, ''), 'idle'),
        CURRENT_TIMESTAMP,
        p_last_run_started_at,
        p_last_run_completed_at,
        p_last_job_status,
        p_last_error_message,
        CURRENT_TIMESTAMP
    )
    ON CONFLICT (runner_name) DO UPDATE SET
        runner_kind = EXCLUDED.runner_kind,
        status = EXCLUDED.status,
        last_seen_at = CURRENT_TIMESTAMP,
        last_run_started_at = COALESCE(EXCLUDED.last_run_started_at, retention_runner_heartbeat.last_run_started_at),
        last_run_completed_at = COALESCE(EXCLUDED.last_run_completed_at, retention_runner_heartbeat.last_run_completed_at),
        last_job_status = COALESCE(EXCLUDED.last_job_status, retention_runner_heartbeat.last_job_status),
        last_error_message = EXCLUDED.last_error_message,
        updated_at = CURRENT_TIMESTAMP;
END;
$$;

CREATE OR REPLACE FUNCTION run_retention_purge(
    p_trigger_source VARCHAR(100) DEFAULT 'app-inline'
)
RETURNS TABLE (
    job_id BIGINT,
    status VARCHAR(20),
    deleted_import_issue INTEGER,
    deleted_import_row INTEGER,
    deleted_import_batch INTEGER,
    deleted_taxonomy_audit INTEGER,
    deleted_graph_audit INTEGER,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    error_message TEXT
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_lock_acquired BOOLEAN := FALSE;
    v_job_id BIGINT := NULL;
    v_started_at TIMESTAMPTZ := CURRENT_TIMESTAMP;
    v_issue_retention_days INTEGER := NULL;
    v_issue_archive_days INTEGER := NULL;
    v_row_retention_days INTEGER := NULL;
    v_row_archive_days INTEGER := NULL;
    v_batch_retention_days INTEGER := NULL;
    v_batch_archive_days INTEGER := NULL;
    v_taxonomy_retention_days INTEGER := NULL;
    v_taxonomy_archive_days INTEGER := NULL;
    v_graph_retention_days INTEGER := NULL;
    v_graph_archive_days INTEGER := NULL;
    v_deleted_import_issue INTEGER := 0;
    v_deleted_import_row INTEGER := 0;
    v_deleted_import_batch INTEGER := 0;
    v_deleted_taxonomy_audit INTEGER := 0;
    v_deleted_graph_audit INTEGER := 0;
BEGIN
    SELECT pg_try_advisory_lock(9042, 1201) INTO v_lock_acquired;
    IF NOT v_lock_acquired THEN
        RETURN QUERY
        SELECT
            NULL::BIGINT,
            'skipped'::VARCHAR(20),
            0, 0, 0, 0, 0,
            v_started_at,
            CURRENT_TIMESTAMP,
            'Retention purge already running'::TEXT;
        RETURN;
    END IF;

    INSERT INTO retention_job_audit (
        trigger_source,
        status,
        started_at
    )
    VALUES (
        COALESCE(NULLIF(p_trigger_source, ''), 'app-inline'),
        'running',
        v_started_at
    )
    RETURNING id INTO v_job_id;

    SELECT retention_days, archive_after_days
    INTO v_issue_retention_days, v_issue_archive_days
    FROM audit_retention_policy
    WHERE policy_key = 'import_issue' AND is_active = TRUE;

    SELECT retention_days, archive_after_days
    INTO v_row_retention_days, v_row_archive_days
    FROM audit_retention_policy
    WHERE policy_key = 'import_row' AND is_active = TRUE;

    SELECT retention_days, archive_after_days
    INTO v_batch_retention_days, v_batch_archive_days
    FROM audit_retention_policy
    WHERE policy_key = 'import_batch' AND is_active = TRUE;

    SELECT retention_days, archive_after_days
    INTO v_taxonomy_retention_days, v_taxonomy_archive_days
    FROM audit_retention_policy
    WHERE policy_key = 'taxonomy_mapping_audit' AND is_active = TRUE;

    SELECT retention_days, archive_after_days
    INTO v_graph_retention_days, v_graph_archive_days
    FROM audit_retention_policy
    WHERE policy_key = 'graph_layout_audit' AND is_active = TRUE;

    IF v_issue_archive_days IS NOT NULL OR v_row_archive_days IS NOT NULL OR v_batch_archive_days IS NOT NULL THEN
        INSERT INTO import_issue_archive
        SELECT CURRENT_TIMESTAMP, v_job_id, i.*
        FROM import_issue i
        WHERE (
            v_issue_archive_days IS NOT NULL
            AND i.created_at < (CURRENT_TIMESTAMP - make_interval(days => v_issue_archive_days))
        )
        OR EXISTS (
            SELECT 1
            FROM import_row r
            WHERE r.id = i.row_id
              AND v_row_archive_days IS NOT NULL
              AND r.created_at < (CURRENT_TIMESTAMP - make_interval(days => v_row_archive_days))
        )
        OR EXISTS (
            SELECT 1
            FROM import_batch b
            WHERE b.id = i.batch_id
              AND v_batch_archive_days IS NOT NULL
              AND b.imported_at < (CURRENT_TIMESTAMP - make_interval(days => v_batch_archive_days))
        )
        ON CONFLICT (id) DO NOTHING;
    END IF;

    IF v_row_archive_days IS NOT NULL THEN
        INSERT INTO import_row_archive
        SELECT CURRENT_TIMESTAMP, v_job_id, r.*
        FROM import_row r
        WHERE r.created_at < (CURRENT_TIMESTAMP - make_interval(days => v_row_archive_days))
        ON CONFLICT (id) DO NOTHING;
    END IF;

    IF v_batch_archive_days IS NOT NULL THEN
        INSERT INTO import_batch_archive
        SELECT CURRENT_TIMESTAMP, v_job_id, b.*
        FROM import_batch b
        WHERE b.imported_at < (CURRENT_TIMESTAMP - make_interval(days => v_batch_archive_days))
        ON CONFLICT (id) DO NOTHING;
    END IF;

    IF v_taxonomy_archive_days IS NOT NULL THEN
        INSERT INTO taxonomy_mapping_audit_archive
        SELECT CURRENT_TIMESTAMP, v_job_id, a.*
        FROM taxonomy_mapping_audit a
        WHERE a.changed_at < (CURRENT_TIMESTAMP - make_interval(days => v_taxonomy_archive_days))
        ON CONFLICT (id) DO NOTHING;
    END IF;

    IF v_graph_archive_days IS NOT NULL THEN
        INSERT INTO graph_layout_audit_archive
        SELECT CURRENT_TIMESTAMP, v_job_id, a.*
        FROM graph_layout_audit a
        WHERE a.changed_at < (CURRENT_TIMESTAMP - make_interval(days => v_graph_archive_days))
        ON CONFLICT (id) DO NOTHING;
    END IF;

    WITH deleted AS (
        DELETE FROM import_issue i
        WHERE (
            v_issue_retention_days IS NOT NULL
            AND i.created_at < (CURRENT_TIMESTAMP - make_interval(days => v_issue_retention_days))
        )
        OR EXISTS (
            SELECT 1
            FROM import_row r
            WHERE r.id = i.row_id
              AND v_row_retention_days IS NOT NULL
              AND r.created_at < (CURRENT_TIMESTAMP - make_interval(days => v_row_retention_days))
        )
        OR EXISTS (
            SELECT 1
            FROM import_batch b
            WHERE b.id = i.batch_id
              AND v_batch_retention_days IS NOT NULL
              AND b.imported_at < (CURRENT_TIMESTAMP - make_interval(days => v_batch_retention_days))
        )
        RETURNING 1
    )
    SELECT COUNT(*)::INTEGER INTO v_deleted_import_issue FROM deleted;

    WITH deleted AS (
        DELETE FROM import_row r
        WHERE v_row_retention_days IS NOT NULL
          AND r.created_at < (CURRENT_TIMESTAMP - make_interval(days => v_row_retention_days))
        RETURNING 1
    )
    SELECT COUNT(*)::INTEGER INTO v_deleted_import_row FROM deleted;

    WITH deleted AS (
        DELETE FROM import_batch b
        WHERE v_batch_retention_days IS NOT NULL
          AND b.imported_at < (CURRENT_TIMESTAMP - make_interval(days => v_batch_retention_days))
        RETURNING 1
    )
    SELECT COUNT(*)::INTEGER INTO v_deleted_import_batch FROM deleted;

    WITH deleted AS (
        DELETE FROM taxonomy_mapping_audit a
        WHERE v_taxonomy_retention_days IS NOT NULL
          AND a.changed_at < (CURRENT_TIMESTAMP - make_interval(days => v_taxonomy_retention_days))
        RETURNING 1
    )
    SELECT COUNT(*)::INTEGER INTO v_deleted_taxonomy_audit FROM deleted;

    WITH deleted AS (
        DELETE FROM graph_layout_audit a
        WHERE v_graph_retention_days IS NOT NULL
          AND a.changed_at < (CURRENT_TIMESTAMP - make_interval(days => v_graph_retention_days))
        RETURNING 1
    )
    SELECT COUNT(*)::INTEGER INTO v_deleted_graph_audit FROM deleted;

    UPDATE retention_job_audit
    SET
        status = 'success',
        deleted_import_issue = v_deleted_import_issue,
        deleted_import_row = v_deleted_import_row,
        deleted_import_batch = v_deleted_import_batch,
        deleted_taxonomy_audit = v_deleted_taxonomy_audit,
        deleted_graph_audit = v_deleted_graph_audit,
        completed_at = CURRENT_TIMESTAMP,
        error_message = NULL
    WHERE id = v_job_id;

    RETURN QUERY
    SELECT
        r.id,
        r.status,
        r.deleted_import_issue,
        r.deleted_import_row,
        r.deleted_import_batch,
        r.deleted_taxonomy_audit,
        r.deleted_graph_audit,
        r.started_at,
        r.completed_at,
        r.error_message
    FROM retention_job_audit r
    WHERE r.id = v_job_id;

    PERFORM pg_advisory_unlock(9042, 1201);
    RETURN;
EXCEPTION WHEN OTHERS THEN
    IF v_job_id IS NULL THEN
        INSERT INTO retention_job_audit (
            trigger_source,
            status,
            started_at,
            completed_at,
            error_message
        )
        VALUES (
            COALESCE(NULLIF(p_trigger_source, ''), 'app-inline'),
            'failed',
            v_started_at,
            CURRENT_TIMESTAMP,
            SQLERRM
        )
        RETURNING id INTO v_job_id;
    ELSE
        UPDATE retention_job_audit
        SET
            status = 'failed',
            deleted_import_issue = v_deleted_import_issue,
            deleted_import_row = v_deleted_import_row,
            deleted_import_batch = v_deleted_import_batch,
            deleted_taxonomy_audit = v_deleted_taxonomy_audit,
            deleted_graph_audit = v_deleted_graph_audit,
            completed_at = CURRENT_TIMESTAMP,
            error_message = SQLERRM
        WHERE id = v_job_id;
    END IF;

    IF v_lock_acquired THEN
        PERFORM pg_advisory_unlock(9042, 1201);
    END IF;

    RETURN QUERY
    SELECT
        r.id,
        r.status,
        r.deleted_import_issue,
        r.deleted_import_row,
        r.deleted_import_batch,
        r.deleted_taxonomy_audit,
        r.deleted_graph_audit,
        r.started_at,
        r.completed_at,
        r.error_message
    FROM retention_job_audit r
    WHERE r.id = v_job_id;
    RETURN;
END;
$$;

CREATE OR REPLACE VIEW v_graphoverviewnodes AS
SELECT
    sc.id AS service_pk,
    CONCAT('svc:', sc.service_id) AS id,
    'service' AS node_kind,
    sc.title,
    sc.service_id,
    sc.service_type_code AS service_type,
    sc.service_status_code AS service_status,
    sc.portfolio_group_code AS portfolio_group,
    (
        SELECT string_agg(sao.domain_code, ',')
        FROM service_available_on sao
        WHERE sao.service_id = sc.id
    ) AS available_on,
    sc.sla_availability,
    sc.graph_x,
    sc.graph_y
FROM service_catalog sc
WHERE sc.is_deleted = FALSE;

CREATE OR REPLACE VIEW v_taxonomyexport AS
SELECT
    c.uuid,
    c.application,
    c.title,
    c.description,
    c.external_id,
    c.data_qualifier,
    c.data_source,
    c.order_num,
    c.ss_overall_status,
    c.ss_baseline_status,
    c.item_status,
    c.item_type,
    c.parent_uuid,
    c.parent_code,
    p.title AS parent_title,
    p.external_id AS parent_external_id,
    c.synced_at
FROM c3_taxonomy c
LEFT JOIN c3_taxonomy p ON p.uuid = c.parent_uuid;

CREATE OR REPLACE VIEW v_pricingexport AS
SELECT
    sc.service_id,
    sf.id AS flavour_pk,
    sf.flavour_code,
    sf.title,
    sf.service_unit,
    sf.price_value,
    sf.currency_code,
    sf.billing_period_code,
    sf.initiation_cost,
    sf.lifecycle_cost,
    sf.lifetime_years,
    sf.nations_rate,
    sf.pricing_note_raw,
    sf.dependency_text,
    sf.flavour_status_code,
    sf.display_order,
    sf.is_orderable
FROM service_flavour sf
JOIN service_catalog sc ON sc.id = sf.service_id
WHERE sf.is_deleted = FALSE AND sc.is_deleted = FALSE;

CREATE OR REPLACE VIEW v_slaexport AS
SELECT
    sc.service_id,
    sl.id AS sla_pk,
    sf.flavour_code,
    sl.support_window_code,
    sl.availability_pct,
    sl.restoration_hours,
    sl.delivery_days,
    sl.priority_model_raw,
    sl.sla_note_raw,
    sl.source_field
FROM service_sla sl
JOIN service_catalog sc ON sc.id = sl.service_id
LEFT JOIN service_flavour sf ON sf.id = sl.flavour_id
WHERE sc.is_deleted = FALSE;

CREATE OR REPLACE VIEW v_c3capabilitymaphierarchyexport AS
WITH mapped AS (
    SELECT DISTINCT c3_uuid
    FROM service_c3_mapping
    WHERE c3_uuid IS NOT NULL
),
mapping_counts AS (
    SELECT c3_uuid, COUNT(*) AS mapping_count
    FROM service_c3_mapping
    WHERE c3_uuid IS NOT NULL
    GROUP BY c3_uuid
)
SELECT
    c.uuid,
    c.external_id,
    c.title,
    c.item_type,
    c.application,
    c.item_status,
    c.parent_uuid,
    c.parent_code,
    p.title AS parent_title,
    p.external_id AS parent_external_id,
    CASE WHEN m.c3_uuid IS NULL THEN FALSE ELSE TRUE END AS is_mapped,
    COALESCE(mc.mapping_count, 0) AS mapping_count,
    c.order_num,
    c.synced_at
FROM c3_taxonomy c
LEFT JOIN c3_taxonomy p ON p.uuid = c.parent_uuid
LEFT JOIN mapped m ON m.c3_uuid = c.uuid
LEFT JOIN mapping_counts mc ON mc.c3_uuid = c.uuid;

CREATE OR REPLACE VIEW v_c3relationshipexport AS
SELECT
    'c3' AS source_kind,
    parent.uuid AS source_id,
    COALESCE(parent.title, parent.external_id, parent.uuid) AS source_label,
    'c3' AS target_kind,
    child.uuid AS target_id,
    COALESCE(child.title, child.external_id, child.uuid) AS target_label,
    'parent_child' AS edge_kind,
    NULL::VARCHAR(50) AS mapping_type_code,
    FALSE AS is_primary
FROM c3_taxonomy child
JOIN c3_taxonomy parent ON parent.uuid = child.parent_uuid

UNION ALL

SELECT
    'service' AS source_kind,
    sc.service_id AS source_id,
    COALESCE(sc.title, sc.service_id) AS source_label,
    'c3' AS target_kind,
    scm.c3_uuid AS target_id,
    COALESCE(c.title, c.external_id, scm.c3_uuid) AS target_label,
    'service_mapping' AS edge_kind,
    scm.mapping_type_code,
    scm.is_primary
FROM service_c3_mapping scm
JOIN service_catalog sc ON sc.id = scm.service_id AND sc.is_deleted = FALSE
LEFT JOIN c3_taxonomy c ON c.uuid = scm.c3_uuid;

CREATE OR REPLACE VIEW v_importbatchexport AS
SELECT
    id,
    filename,
    imported_at,
    imported_by,
    row_count,
    ok_count,
    warn_count,
    error_count,
    parser_version,
    notes,
    source_hash_sha256
FROM import_batch;

CREATE OR REPLACE VIEW v_importrowexport AS
SELECT
    r.id,
    r.batch_id,
    r.row_number,
    r.service_id,
    r.raw_json,
    r.status,
    r.created_at,
    b.filename AS batch_filename,
    b.imported_at AS batch_imported_at
FROM import_row r
JOIN import_batch b ON b.id = r.batch_id;

CREATE OR REPLACE VIEW v_importissueexport AS
SELECT
    i.id,
    i.batch_id,
    i.row_id,
    i.service_id,
    i.severity,
    i.issue_code,
    i.field_name,
    i.raw_value,
    i.message,
    i.resolved,
    i.created_at,
    r.row_number,
    b.filename AS batch_filename,
    b.imported_at AS batch_imported_at
FROM import_issue i
JOIN import_batch b ON b.id = i.batch_id
LEFT JOIN import_row r ON r.id = i.row_id;

CREATE TABLE IF NOT EXISTS import_batch_archive AS
SELECT
    CURRENT_TIMESTAMP::timestamptz AS archived_at,
    NULL::bigint AS retention_job_audit_id,
    b.*
FROM import_batch b
WITH NO DATA;

CREATE TABLE IF NOT EXISTS import_row_archive AS
SELECT
    CURRENT_TIMESTAMP::timestamptz AS archived_at,
    NULL::bigint AS retention_job_audit_id,
    r.*
FROM import_row r
WITH NO DATA;

CREATE TABLE IF NOT EXISTS import_issue_archive AS
SELECT
    CURRENT_TIMESTAMP::timestamptz AS archived_at,
    NULL::bigint AS retention_job_audit_id,
    i.*
FROM import_issue i
WITH NO DATA;

CREATE TABLE IF NOT EXISTS taxonomy_mapping_audit_archive AS
SELECT
    CURRENT_TIMESTAMP::timestamptz AS archived_at,
    NULL::bigint AS retention_job_audit_id,
    a.*
FROM taxonomy_mapping_audit a
WITH NO DATA;

CREATE TABLE IF NOT EXISTS graph_layout_audit_archive AS
SELECT
    CURRENT_TIMESTAMP::timestamptz AS archived_at,
    NULL::bigint AS retention_job_audit_id,
    a.*
FROM graph_layout_audit a
WITH NO DATA;

CREATE INDEX IF NOT EXISTS ix_import_batch_archive_archived_at
    ON import_batch_archive(archived_at);
CREATE UNIQUE INDEX IF NOT EXISTS ux_import_batch_archive_id
    ON import_batch_archive(id);
CREATE INDEX IF NOT EXISTS ix_import_row_archive_archived_at
    ON import_row_archive(archived_at);
CREATE UNIQUE INDEX IF NOT EXISTS ux_import_row_archive_id
    ON import_row_archive(id);
CREATE INDEX IF NOT EXISTS ix_import_issue_archive_archived_at
    ON import_issue_archive(archived_at);
CREATE UNIQUE INDEX IF NOT EXISTS ux_import_issue_archive_id
    ON import_issue_archive(id);
CREATE INDEX IF NOT EXISTS ix_taxonomy_mapping_audit_archive_archived_at
    ON taxonomy_mapping_audit_archive(archived_at);
CREATE UNIQUE INDEX IF NOT EXISTS ux_taxonomy_mapping_audit_archive_id
    ON taxonomy_mapping_audit_archive(id);
CREATE INDEX IF NOT EXISTS ix_graph_layout_audit_archive_archived_at
    ON graph_layout_audit_archive(archived_at);
CREATE UNIQUE INDEX IF NOT EXISTS ux_graph_layout_audit_archive_id
    ON graph_layout_audit_archive(id);

CREATE OR REPLACE VIEW v_importbatcharchiveexport AS
SELECT * FROM import_batch_archive;

CREATE OR REPLACE VIEW v_importrowarchiveexport AS
SELECT * FROM import_row_archive;

CREATE OR REPLACE VIEW v_importissuearchiveexport AS
SELECT * FROM import_issue_archive;

CREATE OR REPLACE VIEW v_taxonomymappingauditarchiveexport AS
SELECT * FROM taxonomy_mapping_audit_archive;

CREATE OR REPLACE VIEW v_graphlayoutauditarchiveexport AS
SELECT * FROM graph_layout_audit_archive;
