-- =============================================================================
-- SERVICE CATALOGUE — PostgreSQL canonical schema
-- 13_install_system.sql | schema: platform
-- Installation system: state machine, migrations, modules, release metadata
-- =============================================================================

SET search_path TO platform, public;

-- ---------------------------------------------------------------------------
-- system_installation
-- Authoritative installation state — single source of truth
-- The frontend reads from it and never derives it on its own
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS system_installation (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    install_status  VARCHAR(30) NOT NULL DEFAULT 'NOT_INSTALLED'
                    CHECK (install_status IN (
                        'NOT_INSTALLED',
                        'INSTALL_IN_PROGRESS',
                        'CORE_INSTALLED',
                        'MODULES_CONFIGURED',
                        'DATA_IMPORT_IN_PROGRESS',
                        'READY',
                        'INSTALL_FAILED',
                        'UPGRADE_REQUIRED',
                        'REPAIR_REQUIRED'
                    )),
    install_mode    VARCHAR(20) NULL
                    CHECK (install_mode IN ('fresh', 'repair', 'upgrade') OR install_mode IS NULL),
    install_lock    BOOLEAN NOT NULL DEFAULT FALSE,
    lock_token      VARCHAR(100) NULL,
    lock_acquired_at TIMESTAMPTZ NULL,
    locked_by       VARCHAR(200) NULL,
    started_at      TIMESTAMPTZ NULL,
    completed_at    TIMESTAMPTZ NULL,
    failed_at       TIMESTAMPTZ NULL,
    failure_reason  TEXT NULL,
    performed_by    VARCHAR(200) NULL,
    install_summary JSONB NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE system_installation IS
    'Authoritative installation state. Only one row is active (id=1). '
    'The frontend reads it and never writes to it. The backend state machine is the only writer.';

-- ---------------------------------------------------------------------------
-- schema_migrations
-- DB migration history — tied to release versions
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS schema_migrations (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    migration_key   VARCHAR(200) NOT NULL UNIQUE,
    migration_label VARCHAR(500) NULL,
    schema_version  VARCHAR(50) NOT NULL,
    app_version     VARCHAR(50) NULL,
    applied_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    applied_by      VARCHAR(200) NULL,
    checksum        VARCHAR(64) NULL,
    duration_ms     INTEGER NULL,
    rollback_sql    TEXT NULL,
    notes           TEXT NULL
);

COMMENT ON TABLE schema_migrations IS
    'History of applied migrations. Basis for upgrade detection '
    'and compatibility checks between image version and DB state.';

-- ---------------------------------------------------------------------------
-- module_registry
-- Registry of activated modules and their state
-- Each module tracks all dimensions independently (schema, seed, UI, API)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS module_registry (
    id                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_code             VARCHAR(50) NOT NULL UNIQUE,
    module_label            VARCHAR(200) NOT NULL,
    is_mandatory            BOOLEAN NOT NULL DEFAULT FALSE,
    enabled                 BOOLEAN NOT NULL DEFAULT FALSE,
    schema_installed        BOOLEAN NOT NULL DEFAULT FALSE,
    reference_seed_installed BOOLEAN NOT NULL DEFAULT FALSE,
    business_data_present   BOOLEAN NOT NULL DEFAULT FALSE,
    ui_visible              BOOLEAN NOT NULL DEFAULT FALSE,
    api_enabled             BOOLEAN NOT NULL DEFAULT FALSE,
    version                 VARCHAR(50) NULL,
    install_order           INTEGER NOT NULL DEFAULT 100,
    config_json             JSONB NULL,
    activated_at            TIMESTAMPTZ NULL,
    activated_by            VARCHAR(200) NULL,
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE module_registry IS
    'Registry of modules and their activation state. '
    'Prevents half-configured states (menu visible, DB not ready). '
    'Foundation for repair and future upgrades.';

-- ---------------------------------------------------------------------------
-- module_installation_history
-- Audit trail for every module activation/deactivation
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS module_installation_history (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_code     VARCHAR(50) NOT NULL REFERENCES module_registry(module_code) ON DELETE CASCADE,
    action          VARCHAR(30) NOT NULL
                    CHECK (action IN ('ACTIVATE', 'DEACTIVATE', 'SCHEMA_MIGRATE', 'SEED_APPLY', 'REPAIR', 'UPGRADE')),
    status          VARCHAR(20) NOT NULL
                    CHECK (status IN ('SUCCESS', 'FAILED', 'PARTIAL', 'ROLLED_BACK')),
    app_version     VARCHAR(50) NULL,
    schema_version  VARCHAR(50) NULL,
    details         JSONB NULL,
    error_detail    TEXT NULL,
    performed_by    VARCHAR(200) NULL,
    performed_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ---------------------------------------------------------------------------
-- release_metadata
-- Binds the running image version to DB state — foundation for upgrade detection
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS release_metadata (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    release_version VARCHAR(50) NOT NULL,
    schema_version  VARCHAR(50) NOT NULL,
    release_notes   TEXT NULL,
    released_at     TIMESTAMPTZ NULL,
    applied_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    applied_by      VARCHAR(200) NULL,
    is_current      BOOLEAN NOT NULL DEFAULT TRUE,
    release_hash    VARCHAR(64) NULL,
    metadata_json   JSONB NULL
);

COMMENT ON TABLE release_metadata IS
    'Binding between image version and DB state. Foundation for upgrade detection. '
    'GitHub releases are tied to tags, so the app needs its own '
    'version handshake with the DB.';

-- ---------------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS ix_schema_migrations_version
    ON schema_migrations(schema_version, applied_at DESC);

CREATE INDEX IF NOT EXISTS ix_module_history_code
    ON module_installation_history(module_code, performed_at DESC);

CREATE INDEX IF NOT EXISTS ix_release_metadata_current
    ON release_metadata(is_current, applied_at DESC)
    WHERE is_current = TRUE;

-- ---------------------------------------------------------------------------
-- Trigger: updated_at auto-update
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION platform.set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE TRIGGER trg_system_installation_updated_at
    BEFORE UPDATE ON system_installation
    FOR EACH ROW EXECUTE FUNCTION platform.set_updated_at();

CREATE OR REPLACE TRIGGER trg_module_registry_updated_at
    BEFORE UPDATE ON module_registry
    FOR EACH ROW EXECUTE FUNCTION platform.set_updated_at();

-- ---------------------------------------------------------------------------
-- Seed: initial install state — NOT_INSTALLED
-- If the row already exists, do not insert again (idempotent)
-- ---------------------------------------------------------------------------
INSERT INTO system_installation (id, install_status, install_lock)
VALUES (1, 'NOT_INSTALLED', FALSE)
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- Seed: module registry — definitions for the two supported modules
-- SERVICE_CATALOGUE_CORE is mandatory and cannot be disabled
-- C3_TAXONOMY is optional
-- ---------------------------------------------------------------------------
INSERT INTO module_registry
    (module_code, module_label, is_mandatory, enabled, schema_installed,
     reference_seed_installed, business_data_present, ui_visible, api_enabled,
     version, install_order)
VALUES
    ('SERVICE_CATALOGUE_CORE',
     'Service Catalogue Core',
     TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE,
     '1.0.0', 1),
    ('C3_TAXONOMY',
     'C3 Capability Taxonomy',
     FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE,
     '1.0.0', 2)
ON CONFLICT (module_code) DO NOTHING;

-- ---------------------------------------------------------------------------
-- Seed: schema migration baseline
-- Records of SQL files applied by the init script
-- Migration keys map to files in backend/db/postgres/schema/
-- ---------------------------------------------------------------------------
INSERT INTO schema_migrations
    (migration_key, migration_label, schema_version, applied_by, notes)
VALUES
    ('00_bootstrap',      'Bootstrap — schemas + extensions',                 '1.0.0', 'init', NULL),
    ('01_platform',       'Platform — AppConfig, Users, RefreshTokens, AuditLog', '1.0.0', 'init', NULL),
    ('02_ref',            'Reference data — lookup tables',                   '1.0.0', 'init', NULL),
    ('03_groups',         'Groups — AppGroup, AppGroupPermission',            '1.0.0', 'init', NULL),
    ('04_core',           'Core — ServiceCatalog main table',                 '1.0.0', 'init', NULL),
    ('05_graph',          'Graph — ServiceRelation, ServiceRelationRaw',      '1.0.0', 'init', NULL),
    ('06_pricing',        'Pricing — ServiceFlavour, ServiceSla',             '1.0.0', 'init', NULL),
    ('07_domains',        'Domains — ServiceAvailableOn M:N',                 '1.0.0', 'init', NULL),
    ('08_ownership',      'Ownership — ServiceRoleAssignment, ServiceC3Mapping', '1.0.0', 'init', NULL),
    ('09_import',         'Import — ImportBatch, ImportRow, ImportIssue',     '1.0.0', 'init', NULL),
    ('10_indexes',        'Indexes — performance indexes',                    '1.0.0', 'init', NULL),
    ('11_c3',             'C3 — taxonomy, entities, links, builder',          '1.0.0', 'init', NULL),
    ('12_exports_retention', 'Exports + retention — views, archive',         '1.0.0', 'init', NULL),
    ('13_install_system', 'Install system — state machine, migrations, modules', '1.0.0', 'init', NULL)
ON CONFLICT (migration_key) DO NOTHING;

-- ---------------------------------------------------------------------------
-- Seed: release metadata
-- ---------------------------------------------------------------------------
INSERT INTO release_metadata
    (release_version, schema_version, release_notes, applied_by, is_current)
VALUES
    ('1.0.0', '1.0.0', 'Initial release — Service Catalogue v2.1', 'init', TRUE)
ON CONFLICT DO NOTHING;
