-- =============================================================================
-- SERVICE CATALOGUE — PostgreSQL canonical schema
-- 15_itil_catalogue_phase1.sql | schema: data
-- Phase 1 additive ITIL-ready catalogue foundation.
-- =============================================================================

SET search_path TO data, public;

-- ── Service-level additive metadata ──────────────────────────────────────────

ALTER TABLE service_catalog
    ADD COLUMN IF NOT EXISTS business_summary TEXT NULL,
    ADD COLUMN IF NOT EXISTS requestable BOOLEAN NULL,
    ADD COLUMN IF NOT EXISTS lifecycle_state VARCHAR(50) NULL,
    ADD COLUMN IF NOT EXISTS target_audience_summary TEXT NULL,
    ADD COLUMN IF NOT EXISTS request_channel_type VARCHAR(100) NULL,
    ADD COLUMN IF NOT EXISTS request_channel_url VARCHAR(2000) NULL,
    ADD COLUMN IF NOT EXISTS approval_required BOOLEAN NULL,
    ADD COLUMN IF NOT EXISTS fulfillment_lead_time_text TEXT NULL,
    ADD COLUMN IF NOT EXISTS review_owner_user_id INTEGER NULL REFERENCES platform.users(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS next_review_due_at TIMESTAMPTZ NULL;

CREATE INDEX IF NOT EXISTS ix_service_catalog_lifecycle_state
    ON service_catalog(lifecycle_state)
    WHERE lifecycle_state IS NOT NULL;

CREATE INDEX IF NOT EXISTS ix_service_catalog_requestable
    ON service_catalog(requestable)
    WHERE requestable IS NOT NULL;

CREATE INDEX IF NOT EXISTS ix_service_catalog_review_owner
    ON service_catalog(review_owner_user_id)
    WHERE review_owner_user_id IS NOT NULL;

-- ── Service Offering — business-facing offering layer beside service_flavour ─

CREATE TABLE IF NOT EXISTS service_offering (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id           BIGINT NOT NULL REFERENCES service_catalog(id) ON DELETE CASCADE,
    offering_code        VARCHAR(100) NOT NULL,
    title                VARCHAR(255) NOT NULL,
    description          TEXT NULL,
    is_default           BOOLEAN NOT NULL DEFAULT FALSE,
    requestable          BOOLEAN NOT NULL DEFAULT FALSE,
    approval_required    BOOLEAN NULL,
    request_channel_type VARCHAR(100) NULL,
    request_channel_url  VARCHAR(2000) NULL,
    lead_time_text       TEXT NULL,
    support_tier_code    VARCHAR(50) NULL,
    status               VARCHAR(50) NOT NULL DEFAULT 'draft',
    display_order        INTEGER NULL,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ux_service_offering_service_code UNIQUE (service_id, offering_code),
    CONSTRAINT ux_service_offering_id_service UNIQUE (id, service_id)
);

CREATE INDEX IF NOT EXISTS ix_service_offering_service
    ON service_offering(service_id);

CREATE INDEX IF NOT EXISTS ix_service_offering_service_sort
    ON service_offering(service_id, display_order NULLS LAST, title);

CREATE UNIQUE INDEX IF NOT EXISTS ux_service_offering_default_per_service
    ON service_offering(service_id)
    WHERE is_default = TRUE;

-- ── Support model ────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS service_support_model (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id         BIGINT NOT NULL REFERENCES service_catalog(id) ON DELETE CASCADE,
    offering_id        BIGINT NULL,
    support_owner_name VARCHAR(255) NULL,
    resolver_group     VARCHAR(255) NULL,
    support_hours_code VARCHAR(50) NULL,
    support_channel    VARCHAR(255) NULL,
    escalation_path    TEXT NULL,
    maintenance_window TEXT NULL,
    review_cadence     VARCHAR(100) NULL,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_service_support_model_offering_service
        FOREIGN KEY (offering_id, service_id)
        REFERENCES service_offering(id, service_id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_service_support_model_service
    ON service_support_model(service_id);

CREATE UNIQUE INDEX IF NOT EXISTS ux_service_support_model_service_level
    ON service_support_model(service_id)
    WHERE offering_id IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ux_service_support_model_offering
    ON service_support_model(offering_id)
    WHERE offering_id IS NOT NULL;

-- ── Audience / eligibility policy ───────────────────────────────────────────

CREATE TABLE IF NOT EXISTS service_audience_policy (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id       BIGINT NOT NULL REFERENCES service_catalog(id) ON DELETE CASCADE,
    offering_id      BIGINT NULL,
    audience_type    VARCHAR(100) NULL,
    business_unit    VARCHAR(255) NULL,
    region_code      VARCHAR(100) NULL,
    eligibility_rule TEXT NULL,
    notes            TEXT NULL,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_service_audience_policy_offering_service
        FOREIGN KEY (offering_id, service_id)
        REFERENCES service_offering(id, service_id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_service_audience_policy_service
    ON service_audience_policy(service_id);

CREATE INDEX IF NOT EXISTS ix_service_audience_policy_offering
    ON service_audience_policy(offering_id)
    WHERE offering_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS ix_service_audience_policy_audience_type
    ON service_audience_policy(audience_type)
    WHERE audience_type IS NOT NULL;

-- ── Operational links ────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS service_operational_link (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id BIGINT NOT NULL REFERENCES service_catalog(id) ON DELETE CASCADE,
    offering_id BIGINT NULL,
    link_type  VARCHAR(100) NULL,
    title      VARCHAR(255) NOT NULL,
    url        VARCHAR(2000) NOT NULL,
    sort_order INTEGER NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_service_operational_link_offering_service
        FOREIGN KEY (offering_id, service_id)
        REFERENCES service_offering(id, service_id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_service_operational_link_service
    ON service_operational_link(service_id);

CREATE INDEX IF NOT EXISTS ix_service_operational_link_service_sort
    ON service_operational_link(service_id, sort_order NULLS LAST, title);

CREATE INDEX IF NOT EXISTS ix_service_operational_link_offering
    ON service_operational_link(offering_id)
    WHERE offering_id IS NOT NULL;

-- ── Migration tracking ───────────────────────────────────────────────────────

INSERT INTO platform.schema_migrations (migration_key, migration_label, schema_version, notes)
VALUES (
    '15_itil_catalogue_phase1',
    'ITIL-ready catalogue Phase 1 — service offerings, support model, audience policy, operational links',
    '2.2.0',
    'Adds additive service-level metadata to data.service_catalog plus data.service_offering, data.service_support_model, data.service_audience_policy, and data.service_operational_link'
)
ON CONFLICT (migration_key) DO UPDATE SET
    migration_label = EXCLUDED.migration_label,
    applied_at      = CURRENT_TIMESTAMP,
    notes           = EXCLUDED.notes;
