-- =============================================================================
-- SERVICE CATALOGUE — PostgreSQL canonical schema
-- 17_spiral_membership.sql | schema: data
-- Multi-spiral membership for C3 entities.
-- =============================================================================

SET search_path TO data, platform, public;

INSERT INTO data.ref_spiral_baseline (spiral_code, spiral_label, is_active, notes)
VALUES
    ('Spiral_4', 'Spiral 4', FALSE, 'Historical FMN spiral baseline; inactive until explicitly enabled.'),
    ('Spiral_5', 'Spiral 5', FALSE, 'FMN Spiral 5 baseline used by Air C2 PDF parity work.'),
    ('Spiral_6', 'Spiral 6 (current baseline)', TRUE, 'Current active baseline for existing C3 seed data.'),
    ('Spiral_7', 'Spiral 7', FALSE, 'Future/imported FMN spiral baseline.')
ON CONFLICT (spiral_code) DO UPDATE SET
    spiral_label = EXCLUDED.spiral_label,
    notes = EXCLUDED.notes;

CREATE TABLE IF NOT EXISTS data.c3_entity_spiral_membership (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_kind        VARCHAR(50)  NOT NULL,
    entity_uuid        VARCHAR(100) NOT NULL,
    spiral_code        VARCHAR(20)  NOT NULL REFERENCES data.ref_spiral_baseline(spiral_code),
    status_in_spiral   VARCHAR(50)  NULL,
    ss_overall_status  VARCHAR(100) NULL,
    ss_baseline_status VARCHAR(100) NULL,
    item_status        VARCHAR(50)  NULL,
    source_run_id      BIGINT NULL REFERENCES data.c3_entity_import_run(id) ON DELETE SET NULL,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_c3_entity_spiral_membership_kind
        CHECK (entity_kind IN ('application', 'data_object', 'c3_service', 'technology_interaction', 'capability')),
    CONSTRAINT uq_c3_entity_spiral_membership
        UNIQUE (entity_kind, entity_uuid, spiral_code)
);

CREATE INDEX IF NOT EXISTS ix_c3_membership_entity
    ON data.c3_entity_spiral_membership(entity_kind, entity_uuid);

CREATE INDEX IF NOT EXISTS ix_c3_membership_spiral
    ON data.c3_entity_spiral_membership(spiral_code);

INSERT INTO data.c3_entity_spiral_membership (
    entity_kind, entity_uuid, spiral_code, status_in_spiral,
    ss_overall_status, ss_baseline_status, item_status
)
SELECT 'application', uuid, 'Spiral_6', NULL, ss_overall_status, ss_baseline_status, item_status
FROM data.c3_application
ON CONFLICT (entity_kind, entity_uuid, spiral_code) DO UPDATE SET
    ss_overall_status = EXCLUDED.ss_overall_status,
    ss_baseline_status = EXCLUDED.ss_baseline_status,
    item_status = EXCLUDED.item_status,
    updated_at = CURRENT_TIMESTAMP;

INSERT INTO data.c3_entity_spiral_membership (
    entity_kind, entity_uuid, spiral_code, status_in_spiral,
    ss_overall_status, ss_baseline_status, item_status
)
SELECT 'data_object', uuid, 'Spiral_6', NULL, ss_overall_status, ss_baseline_status, item_status
FROM data.c3_data_object
ON CONFLICT (entity_kind, entity_uuid, spiral_code) DO UPDATE SET
    ss_overall_status = EXCLUDED.ss_overall_status,
    ss_baseline_status = EXCLUDED.ss_baseline_status,
    item_status = EXCLUDED.item_status,
    updated_at = CURRENT_TIMESTAMP;

INSERT INTO data.c3_entity_spiral_membership (
    entity_kind, entity_uuid, spiral_code, status_in_spiral,
    ss_overall_status, ss_baseline_status, item_status
)
SELECT 'c3_service', uuid, 'Spiral_6', NULL, ss_overall_status, ss_baseline_status, item_status
FROM data.c3_service
ON CONFLICT (entity_kind, entity_uuid, spiral_code) DO UPDATE SET
    ss_overall_status = EXCLUDED.ss_overall_status,
    ss_baseline_status = EXCLUDED.ss_baseline_status,
    item_status = EXCLUDED.item_status,
    updated_at = CURRENT_TIMESTAMP;

INSERT INTO data.c3_entity_spiral_membership (
    entity_kind, entity_uuid, spiral_code, status_in_spiral,
    ss_overall_status, ss_baseline_status, item_status
)
SELECT 'technology_interaction', uuid, 'Spiral_6', NULL, ss_overall_status, ss_baseline_status, item_status
FROM data.c3_technology_interaction
ON CONFLICT (entity_kind, entity_uuid, spiral_code) DO UPDATE SET
    ss_overall_status = EXCLUDED.ss_overall_status,
    ss_baseline_status = EXCLUDED.ss_baseline_status,
    item_status = EXCLUDED.item_status,
    updated_at = CURRENT_TIMESTAMP;

INSERT INTO data.c3_entity_spiral_membership (
    entity_kind, entity_uuid, spiral_code, status_in_spiral,
    ss_overall_status, ss_baseline_status, item_status
)
SELECT 'capability', uuid, 'Spiral_6', NULL, ss_overall_status, ss_baseline_status, item_status
FROM data.c3_taxonomy
WHERE item_type = 'CP'
ON CONFLICT (entity_kind, entity_uuid, spiral_code) DO UPDATE SET
    ss_overall_status = EXCLUDED.ss_overall_status,
    ss_baseline_status = EXCLUDED.ss_baseline_status,
    item_status = EXCLUDED.item_status,
    updated_at = CURRENT_TIMESTAMP;

CREATE OR REPLACE VIEW data.v_c3_entity_membership_matrix AS
SELECT
    entity_kind,
    entity_uuid,
    BOOL_OR(spiral_code = 'Spiral_4') AS in_spiral_4,
    BOOL_OR(spiral_code = 'Spiral_5') AS in_spiral_5,
    BOOL_OR(spiral_code = 'Spiral_6') AS in_spiral_6,
    BOOL_OR(spiral_code = 'Spiral_7') AS in_spiral_7,
    ARRAY_AGG(spiral_code ORDER BY spiral_code) AS spiral_codes,
    MAX(updated_at) AS last_membership_update
FROM data.c3_entity_spiral_membership
GROUP BY entity_kind, entity_uuid;

INSERT INTO platform.schema_migrations (migration_key, migration_label, schema_version, notes)
VALUES (
    '17_spiral_membership',
    'C3 entity multi-spiral membership',
    '2.1.3',
    'Adds c3_entity_spiral_membership, backfills existing C3 entities, seeds Spiral_4/5, and exposes v_c3_entity_membership_matrix.'
)
ON CONFLICT (migration_key) DO UPDATE SET
    migration_label = EXCLUDED.migration_label,
    applied_at = CURRENT_TIMESTAMP,
    notes = EXCLUDED.notes;
