-- =============================================================================
-- SERVICE CATALOGUE — PostgreSQL canonical schema
-- 21_contract_governance.sql | vendor, contract, and governance finding records
-- =============================================================================

SET search_path TO data, public;

CREATE TABLE IF NOT EXISTS vendor (
    vendor_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor_code   VARCHAR(100) NOT NULL UNIQUE,
    vendor_name   VARCHAR(255) NOT NULL,
    vendor_status VARCHAR(50)  NOT NULL DEFAULT 'active',
    website_url   VARCHAR(2000) NULL,
    notes         TEXT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_vendor_status
        CHECK (vendor_status IN ('active', 'inactive', 'archived'))
);

CREATE TABLE IF NOT EXISTS contract (
    contract_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_code        VARCHAR(100) NOT NULL UNIQUE,
    vendor_id            BIGINT NULL REFERENCES vendor(vendor_id) ON DELETE SET NULL,
    title                VARCHAR(255) NOT NULL,
    contract_owner_email VARCHAR(255) NULL,
    status               VARCHAR(50) NOT NULL DEFAULT 'active',
    start_date           DATE NULL,
    end_date             DATE NULL,
    renewal_date         DATE NULL,
    annual_cost          NUMERIC(14,2) NULL,
    currency_code        VARCHAR(10) NULL DEFAULT 'EUR',
    contract_type        VARCHAR(100) NULL,
    support_scope        TEXT NULL,
    sla_summary          TEXT NULL,
    document_url         VARCHAR(2000) NULL,
    notes                TEXT NULL,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by           VARCHAR(255) NULL,
    updated_by           VARCHAR(255) NULL,
    CONSTRAINT chk_contract_status
        CHECK (status IN ('draft', 'active', 'expired', 'terminated', 'archived')),
    CONSTRAINT chk_contract_date_order
        CHECK (start_date IS NULL OR end_date IS NULL OR start_date <= end_date)
);

CREATE INDEX IF NOT EXISTS ix_contract_vendor
    ON contract(vendor_id)
    WHERE vendor_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS ix_contract_status_renewal
    ON contract(status, renewal_date)
    WHERE status IN ('draft', 'active');

CREATE TABLE IF NOT EXISTS contract_service_link (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id    BIGINT NOT NULL REFERENCES contract(contract_id) ON DELETE CASCADE,
    service_id     BIGINT NOT NULL REFERENCES service_catalog(id) ON DELETE CASCADE,
    coverage_scope VARCHAR(100) NULL,
    support_scope  TEXT NULL,
    is_primary     BOOLEAN NOT NULL DEFAULT FALSE,
    valid_from     DATE NULL,
    valid_to       DATE NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by     VARCHAR(255) NULL,
    CONSTRAINT ux_contract_service_link UNIQUE (contract_id, service_id),
    CONSTRAINT chk_contract_service_link_date_order
        CHECK (valid_from IS NULL OR valid_to IS NULL OR valid_from <= valid_to)
);

CREATE INDEX IF NOT EXISTS ix_contract_service_link_service
    ON contract_service_link(service_id);

CREATE TABLE IF NOT EXISTS contract_capability_link (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id      BIGINT NOT NULL REFERENCES contract(contract_id) ON DELETE CASCADE,
    capability_uuid  VARCHAR(100) NOT NULL,
    capability_title VARCHAR(255) NULL,
    link_scope       VARCHAR(100) NULL,
    is_primary       BOOLEAN NOT NULL DEFAULT FALSE,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by       VARCHAR(255) NULL,
    CONSTRAINT ux_contract_capability_link UNIQUE (contract_id, capability_uuid)
);

CREATE INDEX IF NOT EXISTS ix_contract_capability_link_capability
    ON contract_capability_link(capability_uuid);

CREATE TABLE IF NOT EXISTS governance_finding (
    finding_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    finding_key        VARCHAR(255) NOT NULL UNIQUE,
    finding_type       VARCHAR(50) NOT NULL,
    severity           VARCHAR(10) NOT NULL,
    status             VARCHAR(30) NOT NULL DEFAULT 'active',
    source_entity_type VARCHAR(50) NOT NULL,
    source_entity_id   VARCHAR(100) NULL,
    source_entity_key  VARCHAR(255) NULL,
    title              VARCHAR(255) NOT NULL,
    reason             TEXT NOT NULL,
    suggested_action   TEXT NULL,
    target_url         VARCHAR(2000) NULL,
    score              NUMERIC(10,2) NULL,
    payload_json       JSONB NULL,
    first_seen_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at        TIMESTAMPTZ NULL,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_governance_finding_type
        CHECK (finding_type IN ('risk', 'owner_load', 'contract_overlap', 'renewal', 'advisor')),
    CONSTRAINT chk_governance_finding_severity
        CHECK (severity IN ('P0', 'P1', 'P2', 'info')),
    CONSTRAINT chk_governance_finding_status
        CHECK (status IN ('active', 'dismissed', 'resolved'))
);

CREATE INDEX IF NOT EXISTS ix_governance_finding_active
    ON governance_finding(finding_type, severity, last_seen_at DESC)
    WHERE status = 'active';

CREATE INDEX IF NOT EXISTS ix_governance_finding_source
    ON governance_finding(source_entity_type, source_entity_id)
    WHERE source_entity_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS governance_finding_dismissal (
    dismissal_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    finding_id       BIGINT NOT NULL REFERENCES governance_finding(finding_id) ON DELETE CASCADE,
    dismissed_by     VARCHAR(255) NOT NULL,
    dismissed_reason TEXT NOT NULL,
    dismissed_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at       TIMESTAMPTZ NULL
);

CREATE INDEX IF NOT EXISTS ix_governance_finding_dismissal_finding
    ON governance_finding_dismissal(finding_id, dismissed_at DESC);

SET search_path TO platform, public;
INSERT INTO schema_migrations (migration_key, migration_label, schema_version, notes)
VALUES (
    '21_contract_governance',
    'Contract governance foundation',
    '2.3.0',
    'Adds vendor, contract, contract-to-service/capability links, and governance finding dismissal audit tables'
)
ON CONFLICT (migration_key) DO UPDATE SET
    migration_label = EXCLUDED.migration_label,
    applied_at      = CURRENT_TIMESTAMP,
    notes           = EXCLUDED.notes;
