-- =============================================================================
-- SERVICE CATALOGUE — PostgreSQL canonical schema
-- 23_service_portfolio.sql | schema: data
-- Portfolio and governance metadata foundation.
-- =============================================================================

SET search_path TO data, public;

-- ── Reference values ─────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS ref_service_lifecycle_stage (
    code        VARCHAR(50) PRIMARY KEY,
    name        VARCHAR(120) NOT NULL,
    sort_order  INTEGER NOT NULL DEFAULT 100,
    is_active   BOOLEAN NOT NULL DEFAULT TRUE
);

INSERT INTO ref_service_lifecycle_stage (code, name, sort_order, is_active)
VALUES
    ('draft', 'Draft', 10, TRUE),
    ('design', 'Design', 20, TRUE),
    ('active', 'Active', 30, TRUE),
    ('retiring', 'Retiring', 40, TRUE),
    ('retired', 'Retired', 50, TRUE)
ON CONFLICT (code) DO UPDATE SET
    name       = EXCLUDED.name,
    sort_order = EXCLUDED.sort_order,
    is_active  = EXCLUDED.is_active;

CREATE TABLE IF NOT EXISTS ref_service_criticality (
    code        VARCHAR(50) PRIMARY KEY,
    name        VARCHAR(120) NOT NULL,
    sort_order  INTEGER NOT NULL DEFAULT 100,
    is_active   BOOLEAN NOT NULL DEFAULT TRUE
);

INSERT INTO ref_service_criticality (code, name, sort_order, is_active)
VALUES
    ('standard', 'Standard', 10, TRUE),
    ('important', 'Important', 20, TRUE),
    ('mission_critical', 'Mission critical', 30, TRUE)
ON CONFLICT (code) DO UPDATE SET
    name       = EXCLUDED.name,
    sort_order = EXCLUDED.sort_order,
    is_active  = EXCLUDED.is_active;

-- ── Service portfolio ────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS service_portfolio (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_code  VARCHAR(100) NOT NULL UNIQUE,
    title           VARCHAR(255) NOT NULL,
    description     TEXT NULL,
    status_code     VARCHAR(50) NOT NULL DEFAULT 'active',
    owner_group_id  INTEGER NULL REFERENCES platform.app_group(id) ON DELETE SET NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_service_portfolio_status
    ON service_portfolio(status_code);

CREATE INDEX IF NOT EXISTS ix_service_portfolio_owner_group
    ON service_portfolio(owner_group_id)
    WHERE owner_group_id IS NOT NULL;

INSERT INTO service_portfolio (portfolio_code, title, status_code)
SELECT code, name, 'active'
FROM ref_portfolio_group
ON CONFLICT (portfolio_code) DO UPDATE SET
    title      = EXCLUDED.title,
    updated_at = CURRENT_TIMESTAMP;

-- ── Service-level governance metadata ────────────────────────────────────────

ALTER TABLE service_catalog
    ADD COLUMN IF NOT EXISTS portfolio_id BIGINT NULL REFERENCES service_portfolio(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS lifecycle_stage_code VARCHAR(50) NULL REFERENCES ref_service_lifecycle_stage(code),
    ADD COLUMN IF NOT EXISTS review_due_at TIMESTAMPTZ NULL,
    ADD COLUMN IF NOT EXISTS criticality_code VARCHAR(50) NULL REFERENCES ref_service_criticality(code);

UPDATE service_catalog sc
SET portfolio_id = sp.id
FROM service_portfolio sp
WHERE sc.portfolio_id IS NULL
  AND sc.portfolio_group_code = sp.portfolio_code;

UPDATE service_catalog
SET lifecycle_stage_code = CASE LOWER(COALESCE(lifecycle_state, ''))
    WHEN 'draft' THEN 'draft'
    WHEN 'under_review' THEN 'design'
    WHEN 'approved' THEN 'active'
    WHEN 'live' THEN 'active'
    WHEN 'production' THEN 'active'
    WHEN 'active' THEN 'active'
    WHEN 'deprecated' THEN 'retiring'
    WHEN 'retiring' THEN 'retiring'
    WHEN 'retired' THEN 'retired'
    ELSE lifecycle_stage_code
END
WHERE lifecycle_stage_code IS NULL
  AND lifecycle_state IS NOT NULL;

UPDATE service_catalog
SET review_due_at = next_review_due_at
WHERE review_due_at IS NULL
  AND next_review_due_at IS NOT NULL;

CREATE INDEX IF NOT EXISTS ix_service_catalog_portfolio_id
    ON service_catalog(portfolio_id)
    WHERE portfolio_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS ix_service_catalog_lifecycle_stage
    ON service_catalog(lifecycle_stage_code)
    WHERE lifecycle_stage_code IS NOT NULL;

CREATE INDEX IF NOT EXISTS ix_service_catalog_review_due
    ON service_catalog(review_due_at)
    WHERE review_due_at IS NOT NULL;

CREATE INDEX IF NOT EXISTS ix_service_catalog_criticality
    ON service_catalog(criticality_code)
    WHERE criticality_code IS NOT NULL;

-- ── Migration tracking ───────────────────────────────────────────────────────

INSERT INTO platform.schema_migrations (migration_key, migration_label, schema_version, notes)
VALUES (
    '23_service_portfolio',
    'Service portfolio and governance metadata foundation',
    '2.3.0',
    'Adds service portfolios, lifecycle stage reference values, criticality reference values, and service-level portfolio/review metadata'
)
ON CONFLICT (migration_key) DO UPDATE SET
    migration_label = EXCLUDED.migration_label,
    applied_at      = CURRENT_TIMESTAMP,
    notes           = EXCLUDED.notes;
