-- =============================================================================
-- SERVICE CATALOGUE — PostgreSQL canonical schema
-- 42_c3_entity_link_table.sql | schema: data
--
-- Physically merges the seven C3 link tables into data.c3_entity_link:
--   c3_capability_{application,data_object,tin,c3_service}_link
--   c3_technology_interaction_{application,data_object,service}_link
--
-- One row per link; link_kind is the graph edge_kind (see 38). The former
-- table names remain as auto-updatable views over c3_entity_link (with a
-- link_kind default), so existing writers, imports and exports keep working.
-- Views that depended on the old tables are recreated unchanged on top of
-- the compatibility views. Link ids are renumbered (they are only used as
-- transient handles for deleting a link).
-- Idempotent: runs only while the old base tables exist.
-- =============================================================================

SET search_path TO data, public;

CREATE TABLE IF NOT EXISTS c3_entity_link (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    link_kind                 VARCHAR(40)  NOT NULL,
    capability_uuid           VARCHAR(100) NULL REFERENCES c3_taxonomy(uuid) ON DELETE CASCADE,
    technology_interaction_id BIGINT       NULL REFERENCES c3_technology_interaction(id) ON DELETE CASCADE,
    c3_application_id         BIGINT       NULL REFERENCES c3_application(id) ON DELETE CASCADE,
    c3_data_object_id         BIGINT       NULL REFERENCES c3_data_object(id) ON DELETE CASCADE,
    c3_tin_id                 BIGINT       NULL REFERENCES c3_technology_interaction(id) ON DELETE CASCADE,
    c3_service_id             BIGINT       NULL REFERENCES c3_service(id) ON DELETE CASCADE,
    link_role                 VARCHAR(50)  NULL,
    source_slot               VARCHAR(50)  NULL,
    ref_value                 VARCHAR(200) NULL,
    created_at                TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by                VARCHAR(255) NULL,
    CONSTRAINT ck_c3_entity_link_shape CHECK (
        (link_kind = 'capability_application' AND capability_uuid IS NOT NULL AND c3_application_id IS NOT NULL)
     OR (link_kind = 'capability_data_object' AND capability_uuid IS NOT NULL AND c3_data_object_id IS NOT NULL)
     OR (link_kind = 'capability_tin'         AND capability_uuid IS NOT NULL AND c3_tin_id IS NOT NULL)
     OR (link_kind = 'capability_c3_service'  AND capability_uuid IS NOT NULL AND c3_service_id IS NOT NULL)
     OR (link_kind = 'tin_application'  AND technology_interaction_id IS NOT NULL AND c3_application_id IS NOT NULL AND source_slot IS NOT NULL)
     OR (link_kind = 'tin_data_object'  AND technology_interaction_id IS NOT NULL AND c3_data_object_id IS NOT NULL AND source_slot IS NOT NULL)
     OR (link_kind = 'tin_c3_service'   AND technology_interaction_id IS NOT NULL AND c3_service_id IS NOT NULL AND source_slot IS NOT NULL)
    )
);

COMMENT ON TABLE c3_entity_link IS
    'All links from a C3 capability or technology interaction to a C3 entity; link_kind matches the graph edge_kind.';

CREATE UNIQUE INDEX IF NOT EXISTS uq_c3_entity_link_cap_app ON c3_entity_link (capability_uuid, c3_application_id) WHERE link_kind = 'capability_application';
CREATE UNIQUE INDEX IF NOT EXISTS uq_c3_entity_link_cap_do  ON c3_entity_link (capability_uuid, c3_data_object_id) WHERE link_kind = 'capability_data_object';
CREATE UNIQUE INDEX IF NOT EXISTS uq_c3_entity_link_cap_tin ON c3_entity_link (capability_uuid, c3_tin_id)         WHERE link_kind = 'capability_tin';
CREATE UNIQUE INDEX IF NOT EXISTS uq_c3_entity_link_cap_svc ON c3_entity_link (capability_uuid, c3_service_id)     WHERE link_kind = 'capability_c3_service';
CREATE INDEX IF NOT EXISTS ix_c3_entity_link_kind_capability ON c3_entity_link (link_kind, capability_uuid);
CREATE INDEX IF NOT EXISTS ix_c3_entity_link_kind_ti ON c3_entity_link (link_kind, technology_interaction_id, source_slot);
CREATE INDEX IF NOT EXISTS ix_c3_entity_link_application ON c3_entity_link (c3_application_id) WHERE c3_application_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_c3_entity_link_data_object ON c3_entity_link (c3_data_object_id) WHERE c3_data_object_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_c3_entity_link_tin ON c3_entity_link (c3_tin_id) WHERE c3_tin_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_c3_entity_link_service ON c3_entity_link (c3_service_id) WHERE c3_service_id IS NOT NULL;

DO $$
DECLARE
    old_tables CONSTANT TEXT[] := ARRAY[
        'c3_capability_application_link', 'c3_capability_data_object_link',
        'c3_capability_tin_link', 'c3_capability_c3_service_link',
        'c3_technology_interaction_application_link', 'c3_technology_interaction_data_object_link',
        'c3_technology_interaction_service_link'
    ];
    view_row RECORD;
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_class
        WHERE relnamespace = 'data'::regnamespace AND relkind = 'r' AND relname = ANY (old_tables)
    ) THEN
        RETURN;
    END IF;

    -- 1. Copy the links.
    INSERT INTO c3_entity_link (link_kind, capability_uuid, c3_application_id, link_role, created_at, created_by)
    SELECT 'capability_application', capability_uuid, c3_application_id, link_role, created_at, created_by FROM c3_capability_application_link;
    INSERT INTO c3_entity_link (link_kind, capability_uuid, c3_data_object_id, link_role, created_at, created_by)
    SELECT 'capability_data_object', capability_uuid, c3_data_object_id, link_role, created_at, created_by FROM c3_capability_data_object_link;
    INSERT INTO c3_entity_link (link_kind, capability_uuid, c3_tin_id, link_role, created_at, created_by)
    SELECT 'capability_tin', capability_uuid, c3_tin_id, link_role, created_at, created_by FROM c3_capability_tin_link;
    INSERT INTO c3_entity_link (link_kind, capability_uuid, c3_service_id, link_role, created_at, created_by)
    SELECT 'capability_c3_service', capability_uuid, c3_service_id, link_role, created_at, created_by FROM c3_capability_c3_service_link;
    INSERT INTO c3_entity_link (link_kind, technology_interaction_id, c3_application_id, source_slot, ref_value, created_at)
    SELECT 'tin_application', technology_interaction_id, c3_application_id, source_slot, ref_value, created_at FROM c3_technology_interaction_application_link;
    INSERT INTO c3_entity_link (link_kind, technology_interaction_id, c3_data_object_id, source_slot, ref_value, created_at)
    SELECT 'tin_data_object', technology_interaction_id, c3_data_object_id, source_slot, ref_value, created_at FROM c3_technology_interaction_data_object_link;
    INSERT INTO c3_entity_link (link_kind, technology_interaction_id, c3_service_id, source_slot, ref_value, created_at)
    SELECT 'tin_c3_service', technology_interaction_id, c3_service_id, source_slot, ref_value, created_at FROM c3_technology_interaction_service_link;

    -- 2. Remember every view that (transitively) depends on the old tables.
    CREATE TEMP TABLE c3_link_dependent_views ON COMMIT DROP AS
    WITH RECURSIVE base AS (
        SELECT oid FROM pg_class WHERE relnamespace = 'data'::regnamespace AND relname = ANY (old_tables)
    ), deps AS (
        SELECT DISTINCT r.ev_class AS view_oid
        FROM pg_depend d JOIN pg_rewrite r ON r.oid = d.objid JOIN base ON base.oid = d.refobjid
        WHERE r.ev_class <> d.refobjid
        UNION
        SELECT DISTINCT r.ev_class
        FROM pg_depend d JOIN pg_rewrite r ON r.oid = d.objid JOIN deps ON deps.view_oid = d.refobjid
        WHERE r.ev_class <> d.refobjid
    )
    SELECT c.oid AS view_oid, n.nspname AS schema_name, c.relname AS view_name,
           pg_get_viewdef(c.oid) AS definition, obj_description(c.oid, 'pg_class') AS comment
    FROM deps JOIN pg_class c ON c.oid = deps.view_oid JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE c.relkind = 'v';

    -- 3. Replace the tables with compatibility views.
    EXECUTE 'DROP TABLE ' || array_to_string(ARRAY(SELECT 'data.' || quote_ident(t) FROM unnest(old_tables) t), ', ') || ' CASCADE';

    CREATE VIEW c3_capability_application_link AS
        SELECT id, capability_uuid, c3_application_id, link_role, created_at, created_by, link_kind
        FROM c3_entity_link WHERE link_kind = 'capability_application' WITH CASCADED CHECK OPTION;
    CREATE VIEW c3_capability_data_object_link AS
        SELECT id, capability_uuid, c3_data_object_id, link_role, created_at, created_by, link_kind
        FROM c3_entity_link WHERE link_kind = 'capability_data_object' WITH CASCADED CHECK OPTION;
    CREATE VIEW c3_capability_tin_link AS
        SELECT id, capability_uuid, c3_tin_id, link_role, created_at, created_by, link_kind
        FROM c3_entity_link WHERE link_kind = 'capability_tin' WITH CASCADED CHECK OPTION;
    CREATE VIEW c3_capability_c3_service_link AS
        SELECT id, capability_uuid, c3_service_id, link_role, created_at, created_by, link_kind
        FROM c3_entity_link WHERE link_kind = 'capability_c3_service' WITH CASCADED CHECK OPTION;
    CREATE VIEW c3_technology_interaction_application_link AS
        SELECT id, technology_interaction_id, c3_application_id, source_slot, ref_value, created_at, link_kind
        FROM c3_entity_link WHERE link_kind = 'tin_application' WITH CASCADED CHECK OPTION;
    CREATE VIEW c3_technology_interaction_data_object_link AS
        SELECT id, technology_interaction_id, c3_data_object_id, source_slot, ref_value, created_at, link_kind
        FROM c3_entity_link WHERE link_kind = 'tin_data_object' WITH CASCADED CHECK OPTION;
    CREATE VIEW c3_technology_interaction_service_link AS
        SELECT id, technology_interaction_id, c3_service_id, source_slot, ref_value, created_at, link_kind
        FROM c3_entity_link WHERE link_kind = 'tin_c3_service' WITH CASCADED CHECK OPTION;

    ALTER VIEW c3_capability_application_link ALTER COLUMN link_kind SET DEFAULT 'capability_application';
    ALTER VIEW c3_capability_data_object_link ALTER COLUMN link_kind SET DEFAULT 'capability_data_object';
    ALTER VIEW c3_capability_tin_link ALTER COLUMN link_kind SET DEFAULT 'capability_tin';
    ALTER VIEW c3_capability_c3_service_link ALTER COLUMN link_kind SET DEFAULT 'capability_c3_service';
    ALTER VIEW c3_technology_interaction_application_link ALTER COLUMN link_kind SET DEFAULT 'tin_application';
    ALTER VIEW c3_technology_interaction_data_object_link ALTER COLUMN link_kind SET DEFAULT 'tin_data_object';
    ALTER VIEW c3_technology_interaction_service_link ALTER COLUMN link_kind SET DEFAULT 'tin_c3_service';

    -- 4. Recreate the dependent views in their original creation order.
    FOR view_row IN SELECT * FROM c3_link_dependent_views ORDER BY view_oid LOOP
        EXECUTE format('CREATE VIEW %I.%I AS %s', view_row.schema_name, view_row.view_name, view_row.definition);
        IF view_row.comment IS NOT NULL THEN
            EXECUTE format('COMMENT ON VIEW %I.%I IS %L', view_row.schema_name, view_row.view_name, view_row.comment);
        END IF;
    END LOOP;
END $$;

-- Unified read model reads the merged table directly.
DROP VIEW IF EXISTS v_c3_entity_link;
CREATE VIEW v_c3_entity_link AS
SELECT l.link_kind::varchar(40) AS link_kind,
       (CASE WHEN l.capability_uuid IS NOT NULL THEN 'capability' ELSE 'tin' END)::varchar(20) AS source_kind,
       COALESCE(l.capability_uuid, ti.uuid) AS source_uuid,
       l.technology_interaction_id AS source_id,
       (CASE
           WHEN l.c3_application_id IS NOT NULL THEN 'application'
           WHEN l.c3_data_object_id IS NOT NULL THEN 'data_object'
           WHEN l.c3_tin_id IS NOT NULL THEN 'tin'
           ELSE 'c3_service'
       END)::varchar(20) AS target_kind,
       COALESCE(app.id, dob.id, tin.id, svc.id) AS target_id,
       COALESCE(app.uuid, dob.uuid, tin.uuid, svc.uuid) AS target_uuid,
       COALESCE(app.application_code, dob.data_object_code, tin.technology_interaction_code, svc.service_code) AS target_code,
       COALESCE(app.title, dob.title, tin.title, svc.title) AS target_title,
       COALESCE(app.item_status, dob.item_status, tin.item_status, svc.item_status) AS target_item_status,
       COALESCE(l.link_role, l.source_slot) AS link_role
FROM c3_entity_link l
LEFT JOIN c3_technology_interaction ti ON ti.id = l.technology_interaction_id
LEFT JOIN c3_application app ON app.id = l.c3_application_id
LEFT JOIN c3_data_object dob ON dob.id = l.c3_data_object_id
LEFT JOIN c3_technology_interaction tin ON tin.id = l.c3_tin_id
LEFT JOIN c3_service svc ON svc.id = l.c3_service_id;

COMMENT ON VIEW v_c3_entity_link IS
    'Read model over data.c3_entity_link with target entity details; link_kind matches graph edge_kind.';

SET search_path TO platform, public;

INSERT INTO schema_migrations (migration_key, migration_label, schema_version, notes)
VALUES (
    '42_c3_entity_link_table',
    'C3 link tables merged into c3_entity_link',
    '3.9.0',
    'Moves the seven C3 capability/technology-interaction link tables into data.c3_entity_link; the old names are updatable compatibility views.'
)
ON CONFLICT (migration_key) DO UPDATE SET
    migration_label = EXCLUDED.migration_label,
    schema_version  = EXCLUDED.schema_version,
    applied_at      = CURRENT_TIMESTAMP,
    notes           = EXCLUDED.notes;
