\ir ../../schema/04_core.sql
\ir ../../schema/05_graph.sql
\ir ../../schema/06_pricing.sql
\ir ../../schema/07_domains.sql
\ir ../../schema/08_ownership.sql
\ir ../../schema/09_import.sql
\ir ../../schema/15_itil_catalogue_phase1.sql
\ir ../../schema/16_consumer_value.sql
\ir ../../schema/29_reduction_low_risk_cleanup.sql
\ir ../../schema/30_reduction_domain_model_simplification.sql
\ir ../../schema/32_final_reduction_sunset_cleanup.sql
